function results = runBayesianTBDTests()
%% تشغيل اختبارات Bayesian TBD فقط كفحص سريع قبل الدفعة الكاملة.

testsFolder = fileparts(mfilename('fullpath'));
projectRoot = fileparts(testsFolder);

restoredefaultpath;
addpath(fullfile(projectRoot, 'Main'), '-begin');
setupProjectPaths();
addpath(testsFolder, '-end');

testFiles = { ...
    'testPhase3BayesianState.m', ...
    'testPhase3BayesianPropagation.m', ...
    'testPhase3BayesianLikelihood.m', ...
    'testPhase3BayesianMapAndPeaks.m', ...
    'testPhase3BayesianTracks.m', ...
    'testEvidenceMapVisualizationCompatibility.m'};

% شغّل كل ملف اختبار منفردًا. بعض إصدارات MATLAB تُرجع أنواعًا
% فرعية مختلفة من matlab.unittest.Test، ولذلك يفشل دمج suites أفقيًا.
firstSuite = testsuite(fullfile( ...
    testsFolder, ...
    testFiles{1}));
results = run(firstSuite);

for fileIndex = 2:numel(testFiles)
    currentSuite = testsuite(fullfile( ...
        testsFolder, ...
        testFiles{fileIndex}));
    currentResults = run(currentSuite);
    results = [results, currentResults]; %#ok<AGROW>
end
disp(table(results));

fprintf('\nBayesian TBD totals:\n');
fprintf('%d Passed, %d Failed, %d Incomplete.\n', ...
    nnz([results.Passed]), ...
    nnz([results.Failed]), ...
    nnz([results.Incomplete]));

end
