function tests = testPhase2AdaptiveFusion
%% ============================================================
% Test File : testPhase2AdaptiveFusion
%
% Description :
% اختبار صحة الأوزان التكيفية للحساسات والتأكد من:
%
% 1- أن مجموع الأوزان يساوي واحدًا.
% 2- أن الحساس الشاذ يحصل على وزن أقل.
% 3- أن الحساس منخفض الموثوقية يحصل على وزن أقل.
% 4- أن القيم غير الصالحة لا تسبب أوزانًا غير رقمية.
%% ============================================================

tests = functiontests(localfunctions);
% تحويل الدوال المحلية الموجودة في الملف إلى اختبارات MATLAB

end

%% ============================================================
% Test Equal Sensor Conditions
%% ============================================================

function testEqualSensorsReceiveEqualWeights(testCase)

processedPacket = createTestPacket( ...
    [0.60, 0.60, 0.60], ...
    [0.80, 0.80, 0.80]);
% إنشاء ثلاث قراءات متساوية وموثوقيات متساوية

weights = calculateAdaptiveWeights(processedPacket);
% حساب الأوزان التكيفية

weightVector = [ ...
    weights.radar, ...
    weights.thermal, ...
    weights.acoustic];

verifyEqual( ...
    testCase, ...
    sum(weightVector), ...
    1, ...
    'AbsTol', 1e-12);
% التأكد من أن مجموع الأوزان يساوي واحدًا

verifyEqual( ...
    testCase, ...
    weightVector, ...
    [1/3, 1/3, 1/3], ...
    'AbsTol', 1e-12);
% الحساسات المتساوية يجب أن تحصل على أوزان متساوية

end

%% ============================================================
% Test Outlier Sensor Suppression
%% ============================================================

function testOutlierSensorReceivesLowerWeight(testCase)

processedPacket = createTestPacket( ...
    [0.65, 0.66, 0.10], ...
    [0.90, 0.90, 0.90]);
% الرادار والحراري متقاربان بينما الصوتي يعطي قراءة شاذة

weights = calculateAdaptiveWeights(processedPacket);
% حساب الأوزان التكيفية

verifyLessThan( ...
    testCase, ...
    weights.acoustic, ...
    weights.radar);
% يجب أن يكون وزن الحساس الصوتي الشاذ أقل من وزن الرادار

verifyLessThan( ...
    testCase, ...
    weights.acoustic, ...
    weights.thermal);
% يجب أن يكون وزن الحساس الصوتي الشاذ أقل من وزن الحراري

verifyEqual( ...
    testCase, ...
    weights.radar + weights.thermal + weights.acoustic, ...
    1, ...
    'AbsTol', 1e-12);
% التأكد من بقاء مجموع الأوزان مساويًا لواحد

end

%% ============================================================
% Test Reliability Influence
%% ============================================================

function testLowReliabilitySensorReceivesLowerWeight(testCase)

processedPacket = createTestPacket( ...
    [0.50, 0.50, 0.50], ...
    [0.90, 0.25, 0.90]);
% القراءات متساوية لكن موثوقية الحساس الحراري منخفضة

weights = calculateAdaptiveWeights(processedPacket);
% حساب الأوزان التكيفية

verifyLessThan( ...
    testCase, ...
    weights.thermal, ...
    weights.radar);
% الحساس منخفض الموثوقية يجب أن يحصل على وزن أقل

verifyLessThan( ...
    testCase, ...
    weights.thermal, ...
    weights.acoustic);
% مقارنة وزن الحراري بوزن الصوتي الموثوق

end

%% ============================================================
% Test Invalid Input Protection
%% ============================================================

function testInvalidValuesProduceValidWeights(testCase)

processedPacket = createTestPacket( ...
    [NaN, 0.60, Inf], ...
    [NaN, 0.80, 0.70]);
% إنشاء قراءات وموثوقيات تحتوي قيمًا غير صالحة

weights = calculateAdaptiveWeights(processedPacket);
% يجب أن تتعامل الدالة مع القيم غير الصالحة بأمان

weightVector = [ ...
    weights.radar, ...
    weights.thermal, ...
    weights.acoustic];

verifyTrue( ...
    testCase, ...
    all(isfinite(weightVector)));
% جميع الأوزان الناتجة يجب أن تكون أرقامًا صالحة

verifyGreaterThanOrEqual( ...
    testCase, ...
    weightVector, ...
    zeros(1,3));
% لا يُسمح بوجود أوزان سالبة

verifyEqual( ...
    testCase, ...
    sum(weightVector), ...
    1, ...
    'AbsTol', 1e-12);
% مجموع الأوزان يجب أن يبقى مساويًا لواحد

end

%% ============================================================
% Test Packet Helper
%% ============================================================

function processedPacket = ...
    createTestPacket(sensorValues, sensorReliabilities)

processedPacket = struct();
% إنشاء حزمة معالجة وهمية للاختبار

processedPacket.features = struct( ...
    'radarFeature', sensorValues(1), ...
    'thermalFeature', sensorValues(2), ...
    'acousticFeature', sensorValues(3));
% إضافة قراءات الحساسات الثلاثة

processedPacket.qualityReport = struct( ...
    'radarReliability', sensorReliabilities(1), ...
    'thermalReliability', sensorReliabilities(2), ...
    'acousticReliability', sensorReliabilities(3));
% إضافة موثوقية كل حساس

end