function tests = testPhase3BayesianState
%% ============================================================
% Test File : testPhase3BayesianState
%
% Description :
% التحقق من تهيئة حالة التوطين البايزي ومنع إنشاء خرائط
% ذات أحجام أو احتمالات غير صالحة.
%% ============================================================

tests = functiontests(localfunctions);

end

%% ============================================================
% Test Default Initialization
%% ============================================================

function testDefaultInitialization(testCase)

gridSize = [50 50];

state = initializeBayesianLocalizationState(gridSize);

verifyEqual( ...
    testCase, ...
    state.gridSize, ...
    gridSize);

verifySize( ...
    testCase, ...
    state.logOddsMap, ...
    gridSize);

verifySize( ...
    testCase, ...
    state.probabilityMap, ...
    gridSize);

verifySize( ...
    testCase, ...
    state.observationCount, ...
    gridSize);

verifySize( ...
    testCase, ...
    state.weightedObservationSupport, ...
    gridSize);

end

%% ============================================================
% Test Sparse Default Prior
%% ============================================================

function testDefaultPriorRepresentsOneExpectedCell(testCase)

gridSize = [20 25];

state = initializeBayesianLocalizationState(gridSize);

expectedPrior = 1 / prod(gridSize);

verifyEqual( ...
    testCase, ...
    state.priorProbability, ...
    expectedPrior, ...
    'AbsTol', ...
    1e-12);

verifyEqual( ...
    testCase, ...
    state.probabilityMap, ...
    expectedPrior .* ones(gridSize), ...
    'AbsTol', ...
    1e-12);

end

%% ============================================================
% Test Custom Prior
%% ============================================================

function testCustomPriorIsApplied(testCase)

gridSize = [12 18];
customPrior = 0.02;

state = initializeBayesianLocalizationState( ...
    gridSize, ...
    customPrior);

expectedLogOdds = log( ...
    customPrior / ...
    (1 - customPrior));

verifyEqual( ...
    testCase, ...
    state.priorProbability, ...
    customPrior, ...
    'AbsTol', ...
    1e-12);

verifyEqual( ...
    testCase, ...
    state.logOddsMap, ...
    expectedLogOdds .* ones(gridSize), ...
    'AbsTol', ...
    1e-12);

end

%% ============================================================
% Test Empty Diagnostics
%% ============================================================

function testDiagnosticsStartEmpty(testCase)

state = initializeBayesianLocalizationState([10 10]);

verifyEmpty( ...
    testCase, ...
    state.lastProbePosition);

verifyEmpty( ...
    testCase, ...
    state.lastPeaks);

verifyEmpty( ...
    testCase, ...
    state.tracks);

verifyEqual( ...
    testCase, ...
    state.updateCount, ...
    0);

verifyEqual( ...
    testCase, ...
    state.nextTrackID, ...
    1);

end

%% ============================================================
% Test Invalid Grid Size
%% ============================================================

function testInvalidGridSizeIsRejected(testCase)

verifyError( ...
    testCase, ...
    @() initializeBayesianLocalizationState([0 10]), ...
    "initializeBayesianLocalizationState:InvalidGridSize");

verifyError( ...
    testCase, ...
    @() initializeBayesianLocalizationState([10 2.5]), ...
    "initializeBayesianLocalizationState:InvalidGridSize");

verifyError( ...
    testCase, ...
    @() initializeBayesianLocalizationState([10 10 10]), ...
    "initializeBayesianLocalizationState:InvalidGridSize");

end

%% ============================================================
% Test Invalid Prior
%% ============================================================

function testInvalidPriorIsRejected(testCase)

verifyError( ...
    testCase, ...
    @() initializeBayesianLocalizationState([10 10], 0), ...
    "initializeBayesianLocalizationState:InvalidPrior");

verifyError( ...
    testCase, ...
    @() initializeBayesianLocalizationState([10 10], 1), ...
    "initializeBayesianLocalizationState:InvalidPrior");

verifyError( ...
    testCase, ...
    @() initializeBayesianLocalizationState([10 10], NaN), ...
    "initializeBayesianLocalizationState:InvalidPrior");

end