function tests = testPhase3BayesianPropagation
%% ============================================================
% Test File : testPhase3BayesianPropagation
%
% Description :
% اختبار حساب مسار الانتشار نحو خلية مرشحة والتأكد من:
% 1- صحة المسافة وخصائص البيئة.
% 2- عدم استخدام مواقع الضحايا الحقيقية.
% 3- رفض المواقع والمدخلات غير الصالحة.
%% ============================================================

tests = functiontests(localfunctions);

end

%% ============================================================
% Test Geometric Distance
%% ============================================================

function testGeometricDistanceIsCorrect(testCase)

scenario = buildSyntheticScenario();

probePosition = [2 3];
candidatePosition = [5 7];

context = bayesianPropagationContext( ...
    scenario, ...
    probePosition, ...
    candidatePosition);

verifyEqual( ...
    testCase, ...
    context.distance, ...
    5, ...
    'AbsTol', ...
    1e-12);
% المسافة بين النقطتين تمثل مثلث 3-4-5

verifyEqual( ...
    testCase, ...
    context.probePosition, ...
    probePosition);

verifyEqual( ...
    testCase, ...
    context.candidatePosition, ...
    candidatePosition);

verifyGreaterThanOrEqual( ...
    testCase, ...
    context.pathCellCount, ...
    2);

end

%% ============================================================
% Test Environmental Values Are Bounded
%% ============================================================

function testEnvironmentalValuesRemainBounded(testCase)

scenario = buildSyntheticScenario();

context = bayesianPropagationContext( ...
    scenario, ...
    [1 1], ...
    [10 12]);

environmentValues = [ ...
    context.meanDebris, ...
    context.meanAttenuation, ...
    context.meanNoise, ...
    context.obstacleFraction];

verifyGreaterThanOrEqual( ...
    testCase, ...
    environmentValues, ...
    zeros(size(environmentValues)));

verifyLessThanOrEqual( ...
    testCase, ...
    environmentValues, ...
    ones(size(environmentValues)));

end

%% ============================================================
% Test Ground Truth Independence
%% ============================================================

function testGroundTruthDoesNotAffectPropagation(testCase)

scenarioA = buildSyntheticScenario();

scenarioB = scenarioA;

scenarioB.victims = [ ...
    1 1;
    10 12;
    5 6];
% تغيير مواقع الضحايا الحقيقية بالكامل

scenarioB.groundTruth.locations = [ ...
    2 11;
    9 2;
    7 7];
% تغيير Ground Truth

scenarioB.environment.vitalSigns = ...
    rand(scenarioB.gridSize);
% تغيير خريطة الإشارات الحيوية المخفية

contextA = bayesianPropagationContext( ...
    scenarioA, ...
    [3 4], ...
    [8 10]);

contextB = bayesianPropagationContext( ...
    scenarioB, ...
    [3 4], ...
    [8 10]);

verifyEqual( ...
    testCase, ...
    contextA, ...
    contextB);
% يجب أن يبقى السياق مطابقًا لأن الدالة لا تستخدم الحقيقة المخفية

end

%% ============================================================
% Test Missing Maps Use Safe Fallback
%% ============================================================

function testMissingEnvironmentMapsUseZeroFallback(testCase)

scenario = struct();

scenario.gridSize = [8 8];
scenario.environment = struct();

context = bayesianPropagationContext( ...
    scenario, ...
    [2 2], ...
    [7 7]);

verifyEqual( ...
    testCase, ...
    context.meanDebris, ...
    0);

verifyEqual( ...
    testCase, ...
    context.meanAttenuation, ...
    0);

verifyEqual( ...
    testCase, ...
    context.meanNoise, ...
    0);

verifyEqual( ...
    testCase, ...
    context.obstacleFraction, ...
    0);

end

%% ============================================================
% Test Position Outside Grid
%% ============================================================

function testPositionOutsideGridIsRejected(testCase)

scenario = buildSyntheticScenario();

verifyError( ...
    testCase, ...
    @() bayesianPropagationContext( ...
        scenario, ...
        [0 1], ...
        [5 5]), ...
    "bayesianPropagationContext:PositionOutsideGrid");

verifyError( ...
    testCase, ...
    @() bayesianPropagationContext( ...
        scenario, ...
        [2 2], ...
        [11 5]), ...
    "bayesianPropagationContext:PositionOutsideGrid");

end

%% ============================================================
% Test Invalid Scenario
%% ============================================================

function testInvalidScenarioIsRejected(testCase)

invalidScenario = struct();

verifyError( ...
    testCase, ...
    @() bayesianPropagationContext( ...
        invalidScenario, ...
        [1 1], ...
        [2 2]), ...
    "bayesianPropagationContext:InvalidScenario");

end

%% ============================================================
% Synthetic Scenario Fixture
%% ============================================================

function scenario = buildSyntheticScenario()

gridSize = [10 12];

[rowGrid, columnGrid] = ndgrid( ...
    1:gridSize(1), ...
    1:gridSize(2));

scenario = struct();

scenario.gridSize = gridSize;

scenario.environment = struct();

scenario.environment.debris = ...
    (rowGrid - 1) ./ ...
    max(gridSize(1) - 1, 1);

scenario.environment.attenuation = ...
    (columnGrid - 1) ./ ...
    max(gridSize(2) - 1, 1);

scenario.environment.noise = ...
    0.20 .* ones(gridSize);

scenario.environment.obstacles = ...
    false(gridSize);

scenario.environment.obstacles(4:7,6) = true;

scenario.environment.vitalSigns = ...
    zeros(gridSize);
% خريطة مخفية يجب ألا تستخدمها دالة الانتشار

scenario.victims = [4 5];

scenario.groundTruth = struct();

scenario.groundTruth.locations = [4 5];

end