function tests = testPhase3StablePeakConsolidation
%% اختبارات تجميع سجلات الضحايا حول القمم النهائية

tests = functiontests(localfunctions);

end


function setupOnce(testCase)

testsFolder = fileparts(mfilename('fullpath'));
projectRoot = fileparts(testsFolder);

addpath( ...
    fullfile(projectRoot, 'Main'), ...
    '-begin');

resolvedRoot = setupProjectPaths();

testCase.TestData.projectRoot = ...
    resolvedRoot;

end


function testSevenRecordsBecomeThreeVictims(testCase)

peakPositions = [ ...
    8 8;
    8 20;
    20 14];

state = createPeakState( ...
    peakPositions, ...
    [0.80; 0.70; 0.60], ...
    [32 32]);

victims = createEmptyVictimArray();

victims(end+1,1) = createVictim( ...
    1, [7 8], [2 2; 4 2]);

victims(end+1,1) = createVictim( ...
    2, [9 8], [2 2; 6 2]);

victims(end+1,1) = createVictim( ...
    3, [8 19], [2 15; 4 15]);

victims(end+1,1) = createVictim( ...
    4, [8 21], [2 17; 4 17]);

victims(end+1,1) = createVictim( ...
    5, [6 20], [6 17; 6 19]);

victims(end+1,1) = createVictim( ...
    6, [19 14], [17 12; 19 12]);

victims(end+1,1) = createVictim( ...
    7, [21 14], [21 12; 23 12]);

[consolidated, stablePeaks, report] = ...
    consolidateVictimRecordsByStablePeaks( ...
        victims, ...
        state);

verifyEqual(testCase, numel(stablePeaks), 3);
verifyEqual(testCase, numel(consolidated), 3);
verifyEqual(testCase, report.inputRecordCount, 7);
verifyEqual(testCase, report.matchedRecordCount, 7);
verifyEqual(testCase, report.unmatchedRecordCount, 0);

actualPositions = reshape( ...
    [consolidated.position], ...
    2, ...
    [])';

verifyEqual( ...
    testCase, ...
    sortrows(actualPositions), ...
    sortrows(peakPositions));

end


function testUnmatchedRecordIsPreserved(testCase)

state = createPeakState( ...
    [10 10], ...
    0.80, ...
    [40 40]);

victims = createEmptyVictimArray();

victims(end+1,1) = createVictim( ...
    1, [10 11], [8 8; 10 8]);

victims(end+1,1) = createVictim( ...
    2, [30 30], [28 28; 30 28]);

[consolidated, stablePeaks, report] = ...
    consolidateVictimRecordsByStablePeaks( ...
        victims, ...
        state);

verifyEqual(testCase, numel(stablePeaks), 1);
verifyEqual(testCase, numel(consolidated), 2);
verifyEqual(testCase, report.matchedRecordCount, 1);
verifyEqual(testCase, report.unmatchedRecordCount, 1);

actualPositions = reshape( ...
    [consolidated.position], ...
    2, ...
    [])';

verifyTrue( ...
    testCase, ...
    ismember([10 10], actualPositions, 'rows'));

verifyTrue( ...
    testCase, ...
    ismember([30 30], actualPositions, 'rows'));

end


function testOverlappingViewsAreNotDoubleCounted(testCase)

state = createPeakState( ...
    [10 10], ...
    0.80, ...
    [20 20]);

victims = createEmptyVictimArray();

victims(end+1,1) = createVictim( ...
    1, ...
    [9 10], ...
    [1 1; 3 1]);

victims(end+1,1) = createVictim( ...
    2, ...
    [11 10], ...
    [1 1; 3 1]);

[consolidated, stablePeaks, report] = ...
    consolidateVictimRecordsByStablePeaks( ...
        victims, ...
        state); %#ok<ASGLU>

verifyEqual(testCase, numel(consolidated), 1);

verifyEqual( ...
    testCase, ...
    consolidated.independentViewCount, ...
    2);

verifyEqual( ...
    testCase, ...
    size(consolidated.observationPositions,1), ...
    2);

end


function testTwoCloseStablePeaksRemainDistinct(testCase)

peakPositions = [ ...
    10 10;
    10 16];

state = createPeakState( ...
    peakPositions, ...
    [0.80; 0.70], ...
    [24 24]);

victims = createEmptyVictimArray();

victims(end+1,1) = createVictim( ...
    1, [10 10], [8 8; 10 8]);

victims(end+1,1) = createVictim( ...
    2, [10 16], [8 18; 10 18]);

[consolidated, stablePeaks, report] = ...
    consolidateVictimRecordsByStablePeaks( ...
        victims, ...
        state); %#ok<ASGLU>

verifyEqual(testCase, numel(stablePeaks), 2);
verifyEqual(testCase, numel(consolidated), 2);

actualPositions = reshape( ...
    [consolidated.position], ...
    2, ...
    [])';

verifyEqual( ...
    testCase, ...
    sortrows(actualPositions), ...
    sortrows(peakPositions));

end


function state = createPeakState( ...
    peakPositions, ...
    peakValues, ...
    gridSize)

state = struct();

state.evidenceMap = zeros( ...
    gridSize(1), ...
    gridSize(2));

state.observationCount = zeros( ...
    gridSize(1), ...
    gridSize(2));

state.weightSum = zeros( ...
    gridSize(1), ...
    gridSize(2));

for peakIndex = 1:size(peakPositions,1)

    peakRow = peakPositions(peakIndex,1);
    peakColumn = peakPositions(peakIndex,2);

    state.evidenceMap( ...
        peakRow, ...
        peakColumn) = ...
        peakValues(peakIndex);

    state.observationCount( ...
        peakRow, ...
        peakColumn) = 5;

    state.weightSum( ...
        peakRow, ...
        peakColumn) = 5;

end

end


function victims = createEmptyVictimArray()

template = createVictim( ...
    1, ...
    [1 1], ...
    [1 1]);

victims = repmat(template, 0, 1);

end


function victim = createVictim( ...
    victimID, ...
    position, ...
    observationPositions)

currentTime = datetime("now");

independentCount = ...
    size(observationPositions,1);

priorityScore = ...
    0.40 + 0.01 * victimID;

victim = struct( ...
    'id', victimID, ...
    'position', position, ...
    'vitalityIndex', 0.50, ...
    'priorityScore', priorityScore, ...
    'priorityLevel', ...
        classifyPriority(priorityScore), ...
    'firstDetectionTime', currentTime, ...
    'lastUpdateTime', currentTime, ...
    'detectionCount', independentCount, ...
    'independentViewCount', independentCount, ...
    'rawAssociationCount', independentCount, ...
    'observationPositions', observationPositions, ...
    'lastObservationPosition', ...
        observationPositions(end,:));

end
