function tests = testPhase2FusionConfidence
%% ============================================================
% Function Name : testPhase2FusionConfidence
%
% Description :
% اختبار معادلة الثقة الجديدة والتأكد من:
% 1- ارتفاع الثقة للقياسات الموثوقة والمتوافقة.
% 2- عدم انهيار الثقة بسبب حساس شاذ منخفض الوزن.
% 3- انخفاض الثقة عندما تكون جميع الحساسات غير موثوقة.
% 4- بقاء النتيجة دائمًا بين صفر وواحد.
%% ============================================================

tests = functiontests(localfunctions);

end

%% ============================================================
% Test Reliable and Consistent Sensors
%% ============================================================

function testReliableConsistentSensors(testCase)

processedPacket = buildTestPacket( ...
    [0.70, 0.68, 0.72], ...
    [0.90, 0.85, 0.88], ...
    0.87);

weights = buildTestWeights( ...
    [0.34, 0.32, 0.34]);

confidence = confidenceEstimation( ...
    processedPacket, ...
    weights, ...
    0.70);

verifyGreaterThanOrEqual( ...
    testCase, ...
    confidence, ...
    0.75);

verifyLessThanOrEqual( ...
    testCase, ...
    confidence, ...
    1);

end

%% ============================================================
% Test Low-Weight Outlier Sensor
%% ============================================================

function testOutlierSensorDoesNotCollapseConfidence(testCase)

processedPacket = buildTestPacket( ...
    [0.72, 0.70, 0.05], ...
    [0.90, 0.85, 0.15], ...
    0.70);

weights = buildTestWeights( ...
    [0.48, 0.47, 0.05]);

fusionScore = ...
    0.48 * 0.72 + ...
    0.47 * 0.70 + ...
    0.05 * 0.05;

confidence = confidenceEstimation( ...
    processedPacket, ...
    weights, ...
    fusionScore);

verifyGreaterThanOrEqual( ...
    testCase, ...
    confidence, ...
    0.65);

end

%% ============================================================
% Test Unreliable Sensors
%% ============================================================

function testUnreliableSensorsProduceLowConfidence(testCase)

processedPacket = buildTestPacket( ...
    [0.70, 0.68, 0.72], ...
    [0.10, 0.10, 0.10], ...
    0.15);

weights = buildTestWeights( ...
    [1/3, 1/3, 1/3]);

confidence = confidenceEstimation( ...
    processedPacket, ...
    weights, ...
    0.70);

verifyLessThan( ...
    testCase, ...
    confidence, ...
    0.55);

end

%% ============================================================
% Test Confidence Bounds
%% ============================================================

function testConfidenceAlwaysRemainsBounded(testCase)

processedPacket = buildTestPacket( ...
    [NaN, 2, -1], ...
    [Inf, -1, 2], ...
    NaN);

weights = buildTestWeights( ...
    [NaN, -2, Inf]);

confidence = confidenceEstimation( ...
    processedPacket, ...
    weights, ...
    2);

verifyGreaterThanOrEqual( ...
    testCase, ...
    confidence, ...
    0);

verifyLessThanOrEqual( ...
    testCase, ...
    confidence, ...
    1);

verifyTrue( ...
    testCase, ...
    isfinite(confidence));

end

%% ============================================================
% Helper: Build Processed Packet
%% ============================================================

function processedPacket = ...
    buildTestPacket( ...
    sensorValues, ...
    sensorReliabilities, ...
    overallQuality)

processedPacket = struct();

processedPacket.features = struct();

processedPacket.features.radarFeature = ...
    sensorValues(1);

processedPacket.features.thermalFeature = ...
    sensorValues(2);

processedPacket.features.acousticFeature = ...
    sensorValues(3);

processedPacket.qualityReport = struct();

processedPacket.qualityReport.radarReliability = ...
    sensorReliabilities(1);

processedPacket.qualityReport.thermalReliability = ...
    sensorReliabilities(2);

processedPacket.qualityReport.acousticReliability = ...
    sensorReliabilities(3);

processedPacket.qualityReport.overallQuality = ...
    overallQuality;

end

%% ============================================================
% Helper: Build Adaptive Weights
%% ============================================================

function weights = buildTestWeights(weightVector)

weights = struct();

weights.radar = weightVector(1);

weights.thermal = weightVector(2);

weights.acoustic = weightVector(3);

end