function priorityPacket = priorityRankingManager( ...
    scenario, ...
    vitalityPacket)

%% ============================================================
% Function Name : priorityRankingManager
%
% Description :
% حساب أولوية إنقاذ الضحية.
%% ============================================================

[priorityScore, priorityComponents] = ...
    calculatePriorityScore( ...
    scenario, ...
    vitalityPacket);

priorityLevel = ...
    classifyPriority( ...
    priorityScore);

priorityPacket = ...
    buildPriorityPacket( ...
        vitalityPacket, ...
        priorityScore, ...
        priorityLevel, ...
        priorityComponents);

end
