function utilityScore = explorationUtility( ...
    scenario, ...
    currentPosition, ...
    candidatePosition, ...
    suspicionCenter, ...
    fusionScore, ...
    vitalityIndex)
%% ============================================================
% Function Name : explorationUtility
%
% Description :
% حساب قيمة المنفعة لخلية مرشحة أثناء البحث المحلي.
%
% تعتمد قيمة المنفعة على:
% 1- قرب الخلية من مركز الاشتباه.
% 2- نتيجة الدمج التكيفي Fusion Score.
% 3- مؤشر الحيوية Vitality Index.
% 4- سهولة الوصول إلى الخلية.
% 5- تكلفة الحركة داخل الخلية.
% 6- المسافة بين موقع المسبار والخلية المرشحة.
%
% كلما ارتفعت قيمة المنفعة، زادت أولوية فحص الخلية.
%
% Inputs :
% scenario          -> السيناريو الحالي.
% currentPosition   -> موقع المسبار الحالي [row, column].
% candidatePosition -> موقع الخلية المرشحة [row, column].
% suspicionCenter   -> مركز منطقة الاشتباه [row, column].
% fusionScore       -> نتيجة الدمج التكيفي الحالية.
% vitalityIndex     -> مؤشر الحيوية الحالي.
%
% Output :
% utilityScore      -> قيمة المنفعة النهائية بين 0 و1.
%% ============================================================

candidateRow = candidatePosition(1); ...
    % استخراج رقم صف الخلية المرشحة

candidateColumn = candidatePosition(2); ...
    % استخراج رقم عمود الخلية المرشحة

gridRows = scenario.gridSize(1); ...
    % قراءة عدد صفوف بيئة المحاكاة

gridColumns = scenario.gridSize(2); ...
    % قراءة عدد أعمدة بيئة المحاكاة

if candidateRow < 1 || candidateRow > gridRows || ...
        candidateColumn < 1 || candidateColumn > gridColumns
    utilityScore = -inf; ...
        % استبعاد الخلية إذا كانت خارج حدود البيئة
    return; ...
        % الخروج من الدالة
end

if scenario.environment.obstacles( ...
        candidateRow, candidateColumn) == 1
    utilityScore = -inf; ...
        % استبعاد الخلية إذا كانت تمثل عائقًا
    return; ...
        % الخروج من الدالة
end

distanceFromSuspicionCenter = sqrt( ...
    (candidateRow - suspicionCenter(1))^2 + ...
    (candidateColumn - suspicionCenter(2))^2); ...
    % حساب المسافة بين الخلية المرشحة ومركز الاشتباه

spatialSuspicion = exp( ...
    -distanceFromSuspicionCenter / 2); ...
    % تقدير قوة الاشتباه المكاني؛ تقل كلما ابتعدت الخلية عن المركز

distanceFromProbe = sqrt( ...
    (candidateRow - currentPosition(1))^2 + ...
    (candidateColumn - currentPosition(2))^2); ...
    % حساب المسافة بين المسبار والخلية المرشحة

maximumGridDistance = sqrt( ...
    gridRows^2 + gridColumns^2); ...
    % حساب أكبر مسافة نظرية داخل بيئة المحاكاة

normalizedDistance = ...
    distanceFromProbe / maximumGridDistance; ...
    % تطبيع مسافة الحركة لتصبح تقريبًا بين 0 و1

accessibilityValue = ...
    scenario.environment.accessibility( ...
    candidateRow, candidateColumn); ...
    % قراءة سهولة الوصول إلى الخلية المرشحة

movementCostValue = ...
    scenario.environment.movementCost( ...
    candidateRow, candidateColumn); ...
    % قراءة تكلفة الحركة داخل الخلية المرشحة

if movementCostValue >= 999
    utilityScore = -inf; ...
        % استبعاد الخلية إذا كانت تكلفة الحركة تدل على أنها مغلقة
    return; ...
        % الخروج من الدالة
end

maximumValidMovementCost = 8; ...
    % أعلى تكلفة حركة طبيعية مستخدمة في البيئة

normalizedMovementCost = min( ...
    movementCostValue / maximumValidMovementCost, 1); ...
    % تطبيع تكلفة الحركة لتصبح بين 0 و1

fusionScore = max(0, min(1, fusionScore)); ...
    % ضمان بقاء نتيجة الدمج بين 0 و1

vitalityIndex = max(0, min(1, vitalityIndex)); ...
    % ضمان بقاء مؤشر الحيوية بين 0 و1

spatialSuspicion = max(0, min(1, spatialSuspicion)); ...
    % ضمان بقاء الاشتباه المكاني بين 0 و1

accessibilityValue = max(0, min(1, accessibilityValue)); ...
    % ضمان بقاء سهولة الوصول بين 0 و1

weightSpatialSuspicion = 0.25; ...
    % وزن القرب من مركز الاشتباه

weightFusionScore = 0.25; ...
    % وزن نتيجة الدمج التكيفي

weightVitalityIndex = 0.20; ...
    % وزن مؤشر الحيوية

weightAccessibility = 0.15; ...
    % وزن سهولة الوصول

weightMovementCost = 0.10; ...
    % وزن عقوبة تكلفة الحركة

weightTravelDistance = 0.05; ...
    % وزن عقوبة المسافة عن موقع المسبار

utilityScore = ...
    weightSpatialSuspicion * spatialSuspicion + ...
    weightFusionScore * fusionScore + ...
    weightVitalityIndex * vitalityIndex + ...
    weightAccessibility * accessibilityValue - ...
    weightMovementCost * normalizedMovementCost - ...
    weightTravelDistance * normalizedDistance; ...
    % حساب قيمة المنفعة النهائية للخلية المرشحة

utilityScore = max(0, min(1, utilityScore)); ...
    % حصر قيمة المنفعة النهائية بين 0 و1

end