function context = bayesianPropagationContext( ...
    scenario, ...
    probePosition, ...
    candidatePosition)
%% ============================================================
% Function Name : bayesianPropagationContext
%
% Description :
% حساب خصائص مسار الانتشار بين المسبار وخلية مرشحة.
%
% الخلية المرشحة مجرد فرضية مكانية، ولا تستخدم الدالة:
% - scenario.victims
% - scenario.groundTruth
% - environment.vitalSigns
%
% لذلك لا يوجد تسريب لموقع الضحية الحقيقي إلى التوطين.
%% ============================================================

%% ============================================================
% Validate Scenario Grid
%% ============================================================

if ~isstruct(scenario) || ...
        ~isfield(scenario, 'gridSize') || ...
        numel(scenario.gridSize) < 2

    error( ...
        "bayesianPropagationContext:InvalidScenario", ...
        "scenario must contain a valid gridSize.");

end

gridSize = double(scenario.gridSize(1:2));

if any(~isfinite(gridSize)) || ...
        any(gridSize < 1) || ...
        any(gridSize ~= round(gridSize))

    error( ...
        "bayesianPropagationContext:InvalidScenario", ...
        "scenario.gridSize must contain positive integers.");

end

%% ============================================================
% Validate Positions
%% ============================================================

probePosition = validatePosition( ...
    probePosition, ...
    gridSize, ...
    "probePosition");

candidatePosition = validatePosition( ...
    candidatePosition, ...
    gridSize, ...
    "candidatePosition");

%% ============================================================
% Build Straight Propagation Path
%% ============================================================

positionDifference = ...
    candidatePosition - probePosition;

distance = sqrt(sum(positionDifference.^2));
% المسافة الهندسية بين المسبار والخلية المرشحة

sampleCount = max( ...
    2, ...
    ceil(2 * distance) + 1);
% أخذ عينتين تقريبًا لكل خلية على طول المسار

sampleRows = round(linspace( ...
    probePosition(1), ...
    candidatePosition(1), ...
    sampleCount));

sampleColumns = round(linspace( ...
    probePosition(2), ...
    candidatePosition(2), ...
    sampleCount));

sampleRows = max( ...
    1, ...
    min(gridSize(1), sampleRows));

sampleColumns = max( ...
    1, ...
    min(gridSize(2), sampleColumns));

linearIndices = sub2ind( ...
    gridSize, ...
    sampleRows, ...
    sampleColumns);

linearIndices = unique( ...
    linearIndices, ...
    'stable');
% منع عدّ الخلية نفسها أكثر من مرة بسبب التقريب

%% ============================================================
% Read Observable Environmental Maps
%% ============================================================

context = struct();

context.probePosition = probePosition;
context.candidatePosition = candidatePosition;

context.distance = distance;
context.pathCellCount = numel(linearIndices);

context.meanDebris = readEnvironmentMapMean( ...
    scenario, ...
    'debris', ...
    linearIndices, ...
    0);

context.meanAttenuation = readEnvironmentMapMean( ...
    scenario, ...
    'attenuation', ...
    linearIndices, ...
    0);

context.meanNoise = readEnvironmentMapMean( ...
    scenario, ...
    'noise', ...
    linearIndices, ...
    0);

context.obstacleFraction = readEnvironmentMapMean( ...
    scenario, ...
    'obstacles', ...
    linearIndices, ...
    0);

context.meanDebris = clamp01(context.meanDebris);
context.meanAttenuation = clamp01(context.meanAttenuation);
context.meanNoise = clamp01(context.meanNoise);
context.obstacleFraction = clamp01( ...
    context.obstacleFraction);

end

%% ============================================================
% Validate One Grid Position
%% ============================================================

function position = validatePosition( ...
    position, ...
    gridSize, ...
    argumentName)

if ~isnumeric(position) || ...
        numel(position) < 2 || ...
        any(~isfinite(position(1:2)))

    error( ...
        "bayesianPropagationContext:InvalidPosition", ...
        "%s must contain two finite numeric coordinates.", ...
        argumentName);

end

position = double(position(1:2));
position = round(position);

if position(1) < 1 || ...
        position(1) > gridSize(1) || ...
        position(2) < 1 || ...
        position(2) > gridSize(2)

    error( ...
        "bayesianPropagationContext:PositionOutsideGrid", ...
        "%s lies outside the scenario grid.", ...
        argumentName);

end

end

%% ============================================================
% Read Mean Value Along Candidate Path
%% ============================================================

function value = readEnvironmentMapMean( ...
    scenario, ...
    mapName, ...
    linearIndices, ...
    fallbackValue)

if isfield(scenario, 'environment') && ...
        isfield(scenario.environment, mapName)

    environmentMap = ...
        scenario.environment.(mapName);

    if isnumeric(environmentMap) || ...
            islogical(environmentMap)

        value = mean(double( ...
            environmentMap(linearIndices)));

    else

        value = fallbackValue;

    end

else

    value = fallbackValue;

end

end

%% ============================================================
% Clamp Scalar to Unit Interval
%% ============================================================

function value = clamp01(value)

if ~isscalar(value) || ~isfinite(value)
    value = 0;
end

value = max(0, min(1, value));

end