function result = calculateBayesianMeasurementLogBayesFactors( ...
    processedPacket, ...
    scenario, ...
    probePosition, ...
    candidatePosition)
%% ============================================================
% حساب Log Bayes Factor لكل حساس عند خلية مرشحة.
%
% H0: لا توجد ضحية في الخلية المرشحة.
% H1: توجد ضحية مع قوة حيوية وعمق دفن مجهولين.
%
% تُهمّش المتغيرات المجهولة باحتمالات قبلية، ويُستخدم توزيع
% Gaussian censored لمطابقة قص القياس الفيزيائي إلى المجال [0,1].
% لا تقرأ الدالة scenario.victims أو scenario.groundTruth.
%% ============================================================

validateProcessedPacket(processedPacket);

config = constants();
sensorConfigs = sensorConfiguration();
context = bayesianPropagationContext( ...
    scenario, ...
    probePosition, ...
    candidatePosition);

sensorNames = ["radar", "thermal", "acoustic"];
result = struct();
result.context = context;

for sensorIndex = 1:numel(sensorNames)

    sensorName = sensorNames(sensorIndex);
    sensorConfig = sensorConfigs.(char(sensorName));
    measurementValue = processedPacket.features.( ...
        char(sensorName + "Feature"));

    sensorResult = calculateOneSensor( ...
        measurementValue, ...
        sensorName, ...
        sensorConfig, ...
        context, ...
        config.bayesian);

    result.(char(sensorName)) = sensorResult;

end

end


function sensorResult = calculateOneSensor( ...
    measurementValue, ...
    sensorName, ...
    sensorConfig, ...
    context, ...
    bayesianConfig)

measurementValue = clamp01(measurementValue);

normalizedDistance = ...
    context.distance / max(sensorConfig.detectionRange, eps);

distanceTransmission = 1 / ...
    (1 + normalizedDistance^sensorConfig.pathLossExponent);

pathLength = max(1, context.distance);
effectiveObstacleCells = ...
    context.obstacleFraction * context.pathCellCount;

observableMaterialLossDb = ...
    pathLength * ( ...
        sensorConfig.debrisLossDbPerCell * context.meanDebris + ...
        sensorConfig.attenuationLossDbPerCell * ...
            context.meanAttenuation) + ...
    sensorConfig.obstacleLossDbPerCell * ...
        effectiveObstacleCells;

noiseStd = sensorConfig.baseNoiseStd + ...
    sensorConfig.noiseStdScale * ...
    sensorConfig.noiseSensitivity * ...
    context.meanNoise;
noiseStd = max(noiseStd, 1e-6);

logLikelihoodH0 = censoredGaussianLogLikelihood( ...
    measurementValue, ...
    0, ...
    noiseStd);

vitalHypotheses = ...
    bayesianConfig.vitalStrengthHypotheses(:);
vitalPrior = normalizeProbabilityVector( ...
    bayesianConfig.vitalStrengthPrior(:), ...
    numel(vitalHypotheses));

burialHypotheses = ...
    bayesianConfig.burialDepthHypotheses(:);
burialPrior = normalizeProbabilityVector( ...
    bayesianConfig.burialDepthPrior(:), ...
    numel(burialHypotheses));

[vitalGrid, burialGrid] = ndgrid( ...
    vitalHypotheses, ...
    burialHypotheses);
priorWeightGrid = vitalPrior * burialPrior';

totalMaterialLossDb = ...
    observableMaterialLossDb + ...
    sensorConfig.burialLossDb .* burialGrid;
transmissionGrid = max(0, min(1, ...
    distanceTransmission .* ...
    10.^(-totalMaterialLossDb ./ 20)));
baseMeanGrid = max(0, min(1, ...
    vitalGrid .* transmissionGrid));

if string(sensorConfig.sourceModel) == "INTERMITTENT"
    eventProbabilityGrid = min(1, ...
        sensorConfig.eventProbability .* ...
        (0.5 + 0.5 .* vitalGrid));

    inactiveMeans = ...
        sensorConfig.continuousActivityFloor .* baseMeanGrid;
    activeMeans = baseMeanGrid;
    componentMeans = [inactiveMeans(:); activeMeans(:)];
    componentWeights = [ ...
        priorWeightGrid(:) .* ...
            (1 - eventProbabilityGrid(:)); ...
        priorWeightGrid(:) .* eventProbabilityGrid(:)];
else
    componentMeans = baseMeanGrid(:);
    componentWeights = priorWeightGrid(:);
end

componentSigma = hypot( ...
    noiseStd, ...
    componentMeans .* sensorConfig.sourceVariationStd);
componentLogLikelihoods = ...
    censoredGaussianLogLikelihood( ...
        measurementValue, ...
        componentMeans, ...
        componentSigma);
componentLogWeights = log(max( ...
    realmin, ...
    componentWeights));

logLikelihoodH1 = logSumExp( ...
    componentLogLikelihoods + componentLogWeights);

logBayesFactor = logLikelihoodH1 - logLikelihoodH0;
logBayesFactorLimit = ...
    bayesianConfig.singleSensorLogBayesFactorLimit;
logBayesFactor = max( ...
    -logBayesFactorLimit, ...
    min(logBayesFactorLimit, logBayesFactor));

normalizedWeights = exp( ...
    componentLogWeights - logSumExp(componentLogWeights));

sensorResult = struct();
sensorResult.sensorName = sensorName;
sensorResult.measurement = measurementValue;
sensorResult.logLikelihoodH0 = logLikelihoodH0;
sensorResult.logLikelihoodH1 = logLikelihoodH1;
sensorResult.logBayesFactor = logBayesFactor;
sensorResult.expectedSignalMean = sum( ...
    normalizedWeights .* componentMeans);
sensorResult.noiseStd = noiseStd;
sensorResult.distanceTransmission = distanceTransmission;
sensorResult.observableMaterialLossDb = ...
    observableMaterialLossDb;

end


function logLikelihood = censoredGaussianLogLikelihood( ...
    value, ...
    meanValue, ...
    sigma)

sigma = max(1e-6, sigma);
minimumProbability = realmin('double');

if value <= 1e-12
    probability = normalCdf((0 - meanValue) ./ sigma);
    logLikelihood = log(max(minimumProbability, probability));
elseif value >= 1 - 1e-12
    probability = 1 - normalCdf((1 - meanValue) ./ sigma);
    logLikelihood = log(max(minimumProbability, probability));
else
    standardizedValue = (value - meanValue) ./ sigma;
    logLikelihood = ...
        -0.5 * standardizedValue.^2 - ...
        log(sigma) - ...
        0.5 * log(2*pi);
end

end


function probability = normalCdf(value)

probability = 0.5 * (1 + erf(value / sqrt(2)));
probability = max(0, min(1, probability));

end


function value = logSumExp(logValues)

maximumValue = max(logValues);

if ~isfinite(maximumValue)
    value = maximumValue;
else
    value = maximumValue + ...
        log(sum(exp(logValues - maximumValue)));
end

end


function probabilities = normalizeProbabilityVector( ...
    probabilities, ...
    expectedLength)

if numel(probabilities) ~= expectedLength || ...
        any(~isfinite(probabilities)) || ...
        any(probabilities < 0) || ...
        sum(probabilities) <= 0
    error( ...
        "calculateBayesianMeasurementLogBayesFactors:InvalidPrior", ...
        "Bayesian hypothesis priors must be finite and nonnegative.");
end

probabilities = probabilities / sum(probabilities);

end


function validateProcessedPacket(processedPacket)

if ~isstruct(processedPacket) || ...
        ~isfield(processedPacket, 'features') || ...
        ~isfield(processedPacket, 'qualityReport')
    error( ...
        "calculateBayesianMeasurementLogBayesFactors:InvalidPacket", ...
        "processedPacket is missing required fields.");
end

requiredFeatures = { ...
    'radarFeature', ...
    'thermalFeature', ...
    'acousticFeature'};

for fieldIndex = 1:numel(requiredFeatures)
    fieldName = requiredFeatures{fieldIndex};
    if ~isfield(processedPacket.features, fieldName) || ...
            ~isscalar(processedPacket.features.(fieldName)) || ...
            ~isfinite(processedPacket.features.(fieldName))
        error( ...
            "calculateBayesianMeasurementLogBayesFactors:InvalidPacket", ...
            "Processed sensor features must be finite scalars.");
    end
end

end


function value = clamp01(value)

if ~isscalar(value) || ~isfinite(value)
    value = 0;
end
value = max(0, min(1, value));

end
