function [victims, finalPeaks, report] = ...
    consolidateVictimRecordsByBayesianTracks( ...
        victims, ...
        bayesianState)
%% ============================================================
% تثبيت قاعدة الضحايا باستخدام المسارات البايزية المؤكدة فقط.
% لا تستخدم الدالة Ground Truth أو عدد الضحايا الحقيقي.
%% ============================================================

inputRecordCount = numel(victims);
finalPeaks = emptyFinalPeakArray();
report = createReport(inputRecordCount);

if ~isempty(victims)
    report.inputRecordPositions = reshape( ...
        [victims.position], 2, [])';
end

if ~isstruct(bayesianState) || ...
        ~isfield(bayesianState, 'tracks') || ...
        isempty(bayesianState.tracks)
    victims = victims([]);
    return;
end

tracks = normalizeMeasurementResolvedTrackSchema( ...
    bayesianState.tracks);
confirmedMask = false(numel(tracks),1);

for index = 1:numel(tracks)
    confirmedMask(index) = ...
        string(tracks(index).status) == "CONFIRMED";
end

confirmedTracks = tracks(confirmedMask);
rawConfirmedTracks = confirmedTracks;
% الاحتفاظ بأعضاء المسارات الخام لاستخدامها كمراسي مكانية بعد الدمج.
report.rawConfirmedTrackCount = numel(confirmedTracks);

if ~isempty(confirmedTracks)
    report.rawConfirmedTrackPositions = reshape( ...
        [confirmedTracks.position], 2, [])';
end

if isempty(confirmedTracks)
    victims = victims([]);
    return;
end

config = constants();
if isfield(bayesianState, 'localizationMethod') && ...
        lower(string(bayesianState.localizationMethod)) == ...
        "spatialbayesianfusion"
    bayesianConfig = config.spatialBayesian;
else
    bayesianConfig = config.bayesian;
end

trackAssociationDistance = ...
    bayesianConfig.trackAssociationDistance;
if isfield(bayesianConfig, 'trackConsolidationDistance')
    trackConsolidationDistance = ...
        bayesianConfig.trackConsolidationDistance;
else
    trackConsolidationDistance = ...
        trackAssociationDistance;
end

if isfield(bayesianConfig, ...
        'trackConsolidationMaximumEdgeDistance')
    trackConsolidationMaximumEdgeDistance = ...
        bayesianConfig.trackConsolidationMaximumEdgeDistance;
else
    trackConsolidationMaximumEdgeDistance = ...
        trackConsolidationDistance;
end

if isfield(bayesianConfig, ...
        'trackConsolidationMaximumMahalanobisDistance')
    trackConsolidationMaximumMahalanobisDistance = ...
        bayesianConfig.trackConsolidationMaximumMahalanobisDistance;
else
    trackConsolidationMaximumMahalanobisDistance = 0;
end

if isfield(bayesianConfig, ...
        'trackConsolidationMaximumClusterDiameter')
    trackConsolidationMaximumClusterDiameter = ...
        bayesianConfig.trackConsolidationMaximumClusterDiameter;
else
    trackConsolidationMaximumClusterDiameter = inf;
end

if isfield(bayesianConfig, ...
        'trackFragmentAssociationDistance')
    trackFragmentAssociationDistance = ...
        bayesianConfig.trackFragmentAssociationDistance;
else
    trackFragmentAssociationDistance = 0;
end

if isfield(bayesianConfig, ...
        'trackFragmentAssociationAmbiguityMargin')
    trackFragmentAssociationAmbiguityMargin = ...
        bayesianConfig.trackFragmentAssociationAmbiguityMargin;
else
    trackFragmentAssociationAmbiguityMargin = inf;
end

if isfield(bayesianConfig, ...
        'trackFragmentMinimumCoreMembers')
    trackFragmentMinimumCoreMembers = ...
        bayesianConfig.trackFragmentMinimumCoreMembers;
else
    trackFragmentMinimumCoreMembers = 2;
end

if isfield(bayesianConfig, ...
        'trackBasinMaximumValleyDrop')
    trackBasinMaximumValleyDrop = ...
        bayesianConfig.trackBasinMaximumValleyDrop;
else
    trackBasinMaximumValleyDrop = -inf;
end

if isfield(bayesianConfig, ...
        'trackBasinMaximumPeakDistance')
    trackBasinMaximumPeakDistance = ...
        bayesianConfig.trackBasinMaximumPeakDistance;
else
    trackBasinMaximumPeakDistance = inf;
end

if isfield(bayesianConfig, ...
        'trackBasinPeakSearchRadius')
    trackBasinPeakSearchRadius = ...
        bayesianConfig.trackBasinPeakSearchRadius;
else
    trackBasinPeakSearchRadius = 0;
end

if isfield(bayesianConfig, ...
        'trackBasinMinimumPeakLogOdds')
    trackBasinMinimumPeakLogOdds = ...
        bayesianConfig.trackBasinMinimumPeakLogOdds;
else
    trackBasinMinimumPeakLogOdds = inf;
end

if isfield(bayesianConfig, ...
        'trackBasinLineSamplesPerCell')
    trackBasinLineSamplesPerCell = ...
        bayesianConfig.trackBasinLineSamplesPerCell;
else
    trackBasinLineSamplesPerCell = 5;
end

if isfield(bayesianConfig, ...
        'trackBasinMinimumSupportRetention')
    trackBasinMinimumSupportRetention = ...
        bayesianConfig.trackBasinMinimumSupportRetention;
else
    trackBasinMinimumSupportRetention = 0;
end

if isfield(bayesianConfig, ...
        'weakIsolatedBasinMinimumLogOddsGap')
    weakIsolatedBasinMinimumLogOddsGap = ...
        bayesianConfig.weakIsolatedBasinMinimumLogOddsGap;
else
    weakIsolatedBasinMinimumLogOddsGap = inf;
end

if isfield(bayesianConfig, ...
        'weakIsolatedBasinMaximumRelativeSupport')
    weakIsolatedBasinMaximumRelativeSupport = ...
        bayesianConfig.weakIsolatedBasinMaximumRelativeSupport;
else
    weakIsolatedBasinMaximumRelativeSupport = 0;
end

if isfield(bayesianConfig, ...
        'weakIsolatedBasinMaximumRawTracks')
    weakIsolatedBasinMaximumRawTracks = ...
        bayesianConfig.weakIsolatedBasinMaximumRawTracks;
else
    weakIsolatedBasinMaximumRawTracks = 0;
end

if isfield(bayesianConfig,'weakMapBasinMaximumRawTracks')
    weakMapBasinMaximumRawTracks = ...
        bayesianConfig.weakMapBasinMaximumRawTracks;
else
    weakMapBasinMaximumRawTracks = 0;
end
if isfield(bayesianConfig,'weakMapBasinMinimumLogOddsGap')
    weakMapBasinMinimumLogOddsGap = ...
        bayesianConfig.weakMapBasinMinimumLogOddsGap;
else
    weakMapBasinMinimumLogOddsGap = inf;
end
if isfield(bayesianConfig, ...
        'weakMapBasinMaximumRelativeSupport')
    weakMapBasinMaximumRelativeSupport = ...
        bayesianConfig.weakMapBasinMaximumRelativeSupport;
else
    weakMapBasinMaximumRelativeSupport = 0;
end

if isfield(bayesianConfig, ...
        'minimumResolvedRangedViews')
    minimumResolvedRangedViews = ...
        bayesianConfig.minimumResolvedRangedViews;
else
    minimumResolvedRangedViews = inf;
end

if isfield(bayesianConfig, ...
        'resolvedSourceMinimumSeparation')
    resolvedSourceMinimumSeparation = ...
        bayesianConfig.resolvedSourceMinimumSeparation;
else
    resolvedSourceMinimumSeparation = inf;
end

if isfield(bayesianConfig,'resolvedSourceSoftPeakSeparation')
    resolvedSourceSoftPeakSeparation = ...
        bayesianConfig.resolvedSourceSoftPeakSeparation;
else
    resolvedSourceSoftPeakSeparation = ...
        resolvedSourceMinimumSeparation;
end
if isfield(bayesianConfig, ...
        'resolvedSourceMaximumBridgeRetention')
    resolvedSourceMaximumBridgeRetention = ...
        bayesianConfig.resolvedSourceMaximumBridgeRetention;
else
    resolvedSourceMaximumBridgeRetention = 0;
end

[confirmedTracks, trackClusterIndex, ...
        trackClusterDiameters, ...
        compactTrackClusterIndex, ...
        compactTrackClusterDiameters, ...
        absorbedFragmentTrackMask, ...
        fragmentTargetCompactClusterIndex, ...
        fragmentRejectedByDiameterTrackMask, ...
        fragmentRejectedByMeasurementResolutionTrackMask] = ...
    clusterConfirmedTracks( ...
        confirmedTracks, ...
        trackConsolidationDistance, ...
        trackConsolidationMaximumEdgeDistance, ...
        trackConsolidationMaximumMahalanobisDistance, ...
        trackConsolidationMaximumClusterDiameter, ...
        trackFragmentAssociationDistance, ...
        trackFragmentAssociationAmbiguityMargin, ...
        trackFragmentMinimumCoreMembers, ...
        bayesianConfig.minimumIndependentViewDistance, ...
        minimumResolvedRangedViews, ...
        resolvedSourceMinimumSeparation);
% الدمج هنا يعمل على المسارات المؤكدة نفسها قبل مطابقة سجلات الضحايا.
% المرحلة الأولى تكوّن عناقيد مدمجة محدودة القطر. المرحلة الثانية
% تعيد الشظية المنفردة فقط إلى عنقود مدعوم، دون السماح لها بنقل
% الاتصال إلى عنقود آخر أو دمج عنقودين مدعومين مستقلين.

preBasinTrackClusterIndex = trackClusterIndex;
preBasinTrackClusterDiameters = trackClusterDiameters;
basinDiagnostics = createEmptyBasinDiagnostics( ...
    numel(confirmedTracks));

if isfield(bayesianState, 'logOddsMap') && ...
        ~isempty(bayesianState.logOddsMap)
    [confirmedTracks, trackClusterIndex, ...
            trackClusterDiameters, basinDiagnostics] = ...
        consolidateTrackClustersByLogOddsBasins( ...
            rawConfirmedTracks, ...
            confirmedTracks, ...
            trackClusterIndex, ...
            bayesianState.logOddsMap, ...
            bayesianState.weightedObservationSupport, ...
            trackBasinMaximumValleyDrop, ...
            trackBasinMaximumPeakDistance, ...
            trackBasinPeakSearchRadius, ...
            trackBasinMinimumPeakLogOdds, ...
            trackBasinLineSamplesPerCell, ...
            trackBasinMinimumSupportRetention, ...
            weakIsolatedBasinMinimumLogOddsGap, ...
            weakIsolatedBasinMaximumRelativeSupport, ...
            weakIsolatedBasinMaximumRawTracks, ...
            weakMapBasinMinimumLogOddsGap, ...
            weakMapBasinMaximumRelativeSupport, ...
            weakMapBasinMaximumRawTracks, ...
            bayesianConfig.minimumIndependentViewDistance, ...
            minimumResolvedRangedViews, ...
            resolvedSourceMinimumSeparation, ...
            resolvedSourceSoftPeakSeparation, ...
            resolvedSourceMaximumBridgeRetention);
end

report.confirmedTrackCount = numel(confirmedTracks);
report.trackClusterIndex = trackClusterIndex;
report.trackClusterDiameters = trackClusterDiameters;
report.compactTrackClusterIndex = compactTrackClusterIndex;
report.compactTrackClusterDiameters = ...
    compactTrackClusterDiameters;
report.absorbedFragmentTrackMask = ...
    absorbedFragmentTrackMask;
report.fragmentTargetCompactClusterIndex = ...
    fragmentTargetCompactClusterIndex;
report.fragmentRejectedByDiameterTrackMask = ...
    fragmentRejectedByDiameterTrackMask;
report.fragmentRejectedByMeasurementResolutionTrackMask = ...
    fragmentRejectedByMeasurementResolutionTrackMask;
report.preBasinTrackClusterIndex = ...
    preBasinTrackClusterIndex;
report.preBasinTrackClusterDiameters = ...
    preBasinTrackClusterDiameters;
report.basinPeakPositions = ...
    basinDiagnostics.peakPositions;
report.basinPeakLogOdds = ...
    basinDiagnostics.peakLogOdds;
report.basinPeakSupport = ...
    basinDiagnostics.peakSupport;
report.basinPairwisePeakDistances = ...
    basinDiagnostics.pairwisePeakDistances;
report.basinPairwiseValleyDrops = ...
    basinDiagnostics.pairwiseValleyDrops;
report.basinPairwiseSupportRetention = ...
    basinDiagnostics.pairwiseSupportRetention;
report.basinPairwiseTemporalContainment = ...
    basinDiagnostics.pairwiseTemporalContainment;
report.basinPairwiseTemporalJaccard = ...
    basinDiagnostics.pairwiseTemporalJaccard;
report.basinIndependentRangedViewCounts = ...
    basinDiagnostics.independentRangedViewCounts;
report.basinPairwiseMeasurementResolvedVeto = ...
    basinDiagnostics.pairwiseMeasurementResolvedVeto;
report.basinPreToFinalClusterIndex = ...
    basinDiagnostics.preToFinalClusterIndex;
report.basinMergedClusterCount = ...
    basinDiagnostics.mergedClusterCount;
report.basinRejectedPreClusterMask = ...
    basinDiagnostics.rejectedPreClusterMask;
report.basinRejectedClusterCount = ...
    basinDiagnostics.rejectedClusterCount;
report.consolidatedTrackPositions = reshape( ...
    [confirmedTracks.position], 2, [])';

for index = 1:numel(confirmedTracks)
    track = confirmedTracks(index);
    finalPeaks(end+1,1) = struct( ...
        'row', round(track.position(1)), ...
        'column', round(track.position(2)), ...
        'value', track.existenceProbability, ...
        'prominence', track.maximumProbability, ...
        'selectionScore', track.existenceProbability, ...
        'probability', track.existenceProbability, ...
        'uncertaintyRadius', sqrt(max( ...
            eps, trace(track.covariance)))); %#ok<AGROW>
end

if isempty(victims)
    return;
end

maximumDistance = max( ...
    trackAssociationDistance, ...
    config.victimDatabase.associationDistance);
assignments = zeros(numel(victims),1);
assignmentDistances = inf(numel(victims),1);
assignmentGates = zeros(numel(victims),1);
assignmentAnchorTrackID = zeros(numel(victims),1);
usedUncertaintyRescue = false(numel(victims),1);

if isfield(bayesianConfig, ...
        'recordAssociationUncertaintyScale')
    uncertaintyScale = ...
        bayesianConfig.recordAssociationUncertaintyScale;
else
    uncertaintyScale = 0;
end

if isfield(bayesianConfig, ...
        'maximumRecordAssociationDistance')
    maximumRecordAssociationDistance = ...
        bayesianConfig.maximumRecordAssociationDistance;
else
    maximumRecordAssociationDistance = maximumDistance;
end

%% ============================================================
% Stage 1: Conservative Fixed-Gate Association
%% ============================================================

for victimIndex = 1:numel(victims)
    position = victims(victimIndex).position(1:2);

    for trackIndex = 1:numel(confirmedTracks)
        [distance, anchorTrackID] = ...
            calculateRecordToClusterDistance( ...
                position, ...
                trackIndex, ...
                rawConfirmedTracks, ...
                trackClusterIndex, ...
                confirmedTracks(trackIndex));

        if distance <= maximumDistance && ...
                distance < assignmentDistances(victimIndex)
            assignments(victimIndex) = trackIndex;
            assignmentDistances(victimIndex) = distance;
            assignmentGates(victimIndex) = maximumDistance;
            assignmentAnchorTrackID(victimIndex) = ...
                anchorTrackID;
        end
    end
end

%% ============================================================
% Stage 2: Unambiguous Singleton Uncertainty Rescue
%% ============================================================
% لا تُوسع بوابة المطابقة في المشاهد متعددة السجلات أو المسارات، لأن
% عدم يقين مسار زائف قد يحوله إلى كشف نهائي. يسمح بالإنقاذ فقط عندما
% يوجد سجل واحد ومسار مؤكد واحد وفشلت البوابة الثابتة.

isSingletonAssociation = ...
    numel(victims) == 1 && ...
    numel(confirmedTracks) == 1;

if isSingletonAssociation && assignments(1) == 0
    position = victims(1).position(1:2);
    track = confirmedTracks(1);
    uncertaintyRadius = sqrt(max( ...
        eps, trace(track.covariance)));
    expandedGate = min( ...
        maximumRecordAssociationDistance, ...
        maximumDistance + ...
            uncertaintyScale * uncertaintyRadius);
    [distance, anchorTrackID] = ...
        calculateRecordToClusterDistance( ...
            position, ...
            1, ...
            rawConfirmedTracks, ...
            trackClusterIndex, ...
            track);

    if distance <= expandedGate
        assignments(1) = 1;
        assignmentDistances(1) = distance;
        assignmentGates(1) = expandedGate;
        assignmentAnchorTrackID(1) = anchorTrackID;
        usedUncertaintyRescue(1) = true;
    end
end


consolidatedVictims = victims([]);

for trackIndex = 1:numel(confirmedTracks)
    recordIndices = find(assignments == trackIndex);
    if isempty(recordIndices)
        continue;
    end

    track = confirmedTracks(trackIndex);
    assignedRecords = victims(recordIndices);
    [~, baseIndex] = max([assignedRecords.priorityScore]);
    consolidatedVictim = assignedRecords(baseIndex);
    consolidatedVictim.position = round(track.position(1:2));
    consolidatedVictim.vitalityIndex = median( ...
        [assignedRecords.vitalityIndex]);
    consolidatedVictim.victimCondition = ...
        estimateVictimCondition( ...
            consolidatedVictim.vitalityIndex);
    consolidatedVictim.priorityScore = max( ...
        [assignedRecords.priorityScore]);
    consolidatedVictim.independentViewCount = ...
        track.independentViewCount;
    consolidatedVictim.detectionCount = ...
        track.independentViewCount;
    consolidatedVictim.rawAssociationCount = sum( ...
        [assignedRecords.rawAssociationCount]);
    if isfield(assignedRecords, ...
            'hasRangedMeasurementEvidence')
        consolidatedVictim.hasRangedMeasurementEvidence = ...
            any(logical([ ...
                assignedRecords.hasRangedMeasurementEvidence]));
    end
    if isfield(assignedRecords, ...
            'rangedMeasurementAssociationCount')
        consolidatedVictim.rangedMeasurementAssociationCount = ...
            sum([ ...
                assignedRecords.rangedMeasurementAssociationCount]);
    end

    allObservationPositions = zeros(0,2);
    for recordIndex = 1:numel(assignedRecords)
        allObservationPositions = [ ...
            allObservationPositions; ...
            assignedRecords(recordIndex).observationPositions]; %#ok<AGROW>
    end
    allObservationPositions = unique( ...
        allObservationPositions, ...
        'rows', ...
        'stable');
    consolidatedVictim.observationPositions = ...
        allObservationPositions;
    if ~isempty(allObservationPositions)
        consolidatedVictim.lastObservationPosition = ...
            allObservationPositions(end,:);
    end

    consolidatedVictims(end+1,1) = ...
        consolidatedVictim; %#ok<AGROW>
end

[consolidatedVictims,finalPeaks, ...
        rescuedUnmatchedRecordMask, ...
        unmatchedRecordPeakLogOdds, ...
        unmatchedRecordPeakSupport] = ...
    rescueStrongUnmatchedRangedRecords( ...
        victims,assignments,consolidatedVictims, ...
        finalPeaks,rawConfirmedTracks, ...
        bayesianState,bayesianConfig);

victims = consolidatedVictims;
report.matchedRecordCount = nnz(assignments > 0);
report.unmatchedRecordCount = nnz( ...
    assignments == 0 & ...
    ~rescuedUnmatchedRecordMask);
report.consolidatedRecordCount = numel(victims);
report.recordToTrackIndex = assignments;
report.assignmentDistances = assignmentDistances;
report.assignmentGates = assignmentGates;
report.assignmentAnchorTrackID = assignmentAnchorTrackID;
report.usedUncertaintyRescue = usedUncertaintyRescue;
report.rescuedUnmatchedRecordMask = ...
    rescuedUnmatchedRecordMask;
report.rescuedUnmatchedRecordCount = ...
    nnz(rescuedUnmatchedRecordMask);
report.unmatchedRecordPeakLogOdds = ...
    unmatchedRecordPeakLogOdds;
report.unmatchedRecordPeakSupport = ...
    unmatchedRecordPeakSupport;

end


function report = createReport(inputRecordCount)

report = struct();
report.inputRecordCount = inputRecordCount;
report.rawConfirmedTrackCount = 0;
report.confirmedTrackCount = 0;
report.matchedRecordCount = 0;
report.unmatchedRecordCount = inputRecordCount;
report.consolidatedRecordCount = 0;
report.recordToTrackIndex = zeros(inputRecordCount,1);
report.assignmentDistances = inf(inputRecordCount,1);
report.trackClusterIndex = zeros(0,1);
report.trackClusterDiameters = zeros(0,1);
report.compactTrackClusterIndex = zeros(0,1);
report.compactTrackClusterDiameters = zeros(0,1);
report.absorbedFragmentTrackMask = false(0,1);
report.fragmentTargetCompactClusterIndex = zeros(0,1);
report.fragmentRejectedByDiameterTrackMask = false(0,1);
report.fragmentRejectedByMeasurementResolutionTrackMask = ...
    false(0,1);
report.preBasinTrackClusterIndex = zeros(0,1);
report.preBasinTrackClusterDiameters = zeros(0,1);
report.basinPeakPositions = zeros(0,2);
report.basinPeakLogOdds = zeros(0,1);
report.basinPeakSupport = zeros(0,1);
report.basinPairwisePeakDistances = zeros(0,0);
report.basinPairwiseValleyDrops = zeros(0,0);
report.basinPairwiseSupportRetention = zeros(0,0);
report.basinPairwiseTemporalContainment = zeros(0,0);
report.basinPairwiseTemporalJaccard = zeros(0,0);
report.basinIndependentRangedViewCounts = zeros(0,1);
report.basinPairwiseMeasurementResolvedVeto = false(0,0);
report.basinPreToFinalClusterIndex = zeros(0,1);
report.basinMergedClusterCount = 0;
report.basinRejectedPreClusterMask = false(0,1);
report.basinRejectedClusterCount = 0;
report.assignmentGates = zeros(inputRecordCount,1);
report.assignmentAnchorTrackID = zeros(inputRecordCount,1);
report.usedUncertaintyRescue = false(inputRecordCount,1);
report.rescuedUnmatchedRecordMask = ...
    false(inputRecordCount,1);
report.rescuedUnmatchedRecordCount = 0;
report.unmatchedRecordPeakLogOdds = ...
    -inf(inputRecordCount,1);
report.unmatchedRecordPeakSupport = ...
    zeros(inputRecordCount,1);
report.inputRecordPositions = zeros(0,2);
report.rawConfirmedTrackPositions = zeros(0,2);
report.consolidatedTrackPositions = zeros(0,2);

end


function [consolidatedVictims,finalPeaks,rescuedMask, ...
        recordPeakLogOdds,recordPeakSupport] = ...
    rescueStrongUnmatchedRangedRecords( ...
        inputVictims,assignments,consolidatedVictims, ...
        finalPeaks,rawConfirmedTracks,bayesianState,config)
% إنقاذ محافظ لسجل UWB قوي لم يستطع المتتبع تكوين مسار مؤكد له.
% لا يكفي السجل منفردًا: يلزم تعدد المشاهدات، وتكرار القياس المباشر،
% ودليل خريطة قوي، وانفصال عن جميع المسارات والكشوف المقبولة.

numberOfRecords = numel(inputVictims);
rescuedMask = false(numberOfRecords,1);
recordPeakLogOdds = -inf(numberOfRecords,1);
recordPeakSupport = zeros(numberOfRecords,1);

requiredConfigFields = { ...
    'unmatchedRangedRecordRescueMinimumViews', ...
    'unmatchedRangedRecordRescueMinimumAssociations', ...
    'unmatchedRangedRecordRescueMinimumLogOdds', ...
    'unmatchedRangedRecordRescueMinimumSupport', ...
    'unmatchedRangedRecordRescueMinimumSeparation', ...
    'unmatchedRangedRecordRescuePeakSearchRadius'};
requiredStateFields = {'logOddsMap','weightedObservationSupport'};

if isempty(inputVictims) || ...
        ~all(isfield(config,requiredConfigFields)) || ...
        ~all(isfield(bayesianState,requiredStateFields)) || ...
        isempty(bayesianState.logOddsMap) || ...
        ~isequal(size(bayesianState.logOddsMap), ...
            size(bayesianState.weightedObservationSupport))
    return;
end

rawTrackPositions = zeros(0,2);
if ~isempty(rawConfirmedTracks)
    rawTrackPositions = reshape( ...
        [rawConfirmedTracks.position],2,[])';
end

candidateIndices = zeros(0,1);
candidateScores = zeros(0,1);

for recordIndex = find(assignments == 0)'
    record = inputVictims(recordIndex);
    hasRangedEvidence = ...
        isfield(record,'hasRangedMeasurementEvidence') && ...
        logical(record.hasRangedMeasurementEvidence);
    rangedAssociationCount = 0;
    if isfield(record,'rangedMeasurementAssociationCount') && ...
            isfinite(record.rangedMeasurementAssociationCount)
        rangedAssociationCount = ...
            record.rangedMeasurementAssociationCount;
    end
    independentViewCount = 0;
    if isfield(record,'independentViewCount') && ...
            isfinite(record.independentViewCount)
        independentViewCount = record.independentViewCount;
    end

    if ~hasRangedEvidence || ...
            rangedAssociationCount < ...
                config.unmatchedRangedRecordRescueMinimumAssociations || ...
            independentViewCount < ...
                config.unmatchedRangedRecordRescueMinimumViews
        continue;
    end

    [peakPosition,peakLogOdds] = ...
        findStrongestLocalLogOddsPeak( ...
            bayesianState.logOddsMap, ...
            record.position(1:2), ...
            config.unmatchedRangedRecordRescuePeakSearchRadius);
    peakSupport = bayesianState.weightedObservationSupport( ...
        peakPosition(1),peakPosition(2));
    recordPeakLogOdds(recordIndex) = peakLogOdds;
    recordPeakSupport(recordIndex) = peakSupport;

    if ~isfinite(peakLogOdds) || ...
            ~isfinite(peakSupport) || ...
            peakLogOdds < ...
            config.unmatchedRangedRecordRescueMinimumLogOdds || ...
            peakSupport < ...
            config.unmatchedRangedRecordRescueMinimumSupport
        continue;
    end

    if ~isempty(rawTrackPositions)
        trackDistances = hypot( ...
            rawTrackPositions(:,1)-record.position(1), ...
            rawTrackPositions(:,2)-record.position(2));
        if any(trackDistances < ...
                config.unmatchedRangedRecordRescueMinimumSeparation)
            continue;
        end
    end

    candidateIndices(end+1,1) = recordIndex; %#ok<AGROW>
    candidateScores(end+1,1) = ... %#ok<AGROW>
        peakLogOdds + log1p(max(0,peakSupport)) + ...
        0.05*independentViewCount + ...
        0.01*rangedAssociationCount;
end

if isempty(candidateIndices)
    return;
end

[~,candidateOrder] = sort(candidateScores,'descend');
candidateIndices = candidateIndices(candidateOrder);
acceptedPositions = zeros(0,2);
if ~isempty(consolidatedVictims)
    acceptedPositions = reshape( ...
        [consolidatedVictims.position],2,[])';
end

for candidateOffset = 1:numel(candidateIndices)
    recordIndex = candidateIndices(candidateOffset);
    record = inputVictims(recordIndex);
    recordPosition = double(record.position(1:2));

    if ~isempty(acceptedPositions)
        acceptedDistances = hypot( ...
            acceptedPositions(:,1)-recordPosition(1), ...
            acceptedPositions(:,2)-recordPosition(2));
        if any(acceptedDistances < ...
                config.unmatchedRangedRecordRescueMinimumSeparation)
            continue;
        end
    end

    record.position = round(recordPosition);
    consolidatedVictims(end+1,1) = record; %#ok<AGROW>
    acceptedPositions(end+1,:) = recordPosition; %#ok<AGROW>
    rescuedMask(recordIndex) = true;

    probability = 1/(1+exp( ...
        -recordPeakLogOdds(recordIndex)));
    finalPeaks(end+1,1) = struct( ... %#ok<AGROW>
        'row',record.position(1), ...
        'column',record.position(2), ...
        'value',probability, ...
        'prominence',recordPeakLogOdds(recordIndex), ...
        'selectionScore',probability, ...
        'probability',probability, ...
        'uncertaintyRadius',1.0);
end

end


function [distance, anchorTrackID] = ...
    calculateRecordToClusterDistance( ...
        recordPosition, ...
        targetClusterIndex, ...
        rawTracks, ...
        rawTrackClusterIndex, ...
        mergedTrack)

memberIndices = find( ...
    rawTrackClusterIndex == targetClusterIndex);

if isempty(memberIndices)
    distance = hypot( ...
        recordPosition(1) - mergedTrack.position(1), ...
        recordPosition(2) - mergedTrack.position(2));
    anchorTrackID = mergedTrack.id;
    return;
end

memberPositions = reshape( ...
    [rawTracks(memberIndices).position], ...
    2, ...
    [])';
memberDistances = hypot( ...
    memberPositions(:,1) - recordPosition(1), ...
    memberPositions(:,2) - recordPosition(2));
[distance, localAnchorIndex] = min(memberDistances);
anchorTrackID = ...
    rawTracks(memberIndices(localAnchorIndex)).id;

end


function peaks = emptyFinalPeakArray()

peaks = struct( ...
    'row', {}, ...
    'column', {}, ...
    'value', {}, ...
    'prominence', {}, ...
    'selectionScore', {}, ...
    'probability', {}, ...
    'uncertaintyRadius', {});

end


function [mergedTracks, clusterIndex, clusterDiameters, ...
        compactClusterIndex, compactClusterDiameters, ...
        absorbedFragmentTrackMask, ...
        fragmentTargetCompactClusterIndex, ...
        fragmentRejectedByDiameterTrackMask, ...
        fragmentRejectedByMeasurementResolutionTrackMask] = ...
    clusterConfirmedTracks( ...
        tracks, ...
        mergeDistance, ...
        maximumEdgeDistance, ...
        maximumMahalanobisDistance, ...
        maximumClusterDiameter, ...
        fragmentAssociationDistance, ...
        fragmentAssociationAmbiguityMargin, ...
        fragmentMinimumCoreMembers, ...
        minimumIndependentViewDistance, ...
        minimumResolvedRangedViews, ...
        resolvedSourceMinimumSeparation)

numberOfTracks = numel(tracks);
clusterIndex = zeros(numberOfTracks,1);
clusterDiameters = zeros(0,1);
compactClusterIndex = zeros(numberOfTracks,1);
compactClusterDiameters = zeros(0,1);
absorbedFragmentTrackMask = false(numberOfTracks,1);
fragmentTargetCompactClusterIndex = zeros(numberOfTracks,1);
fragmentRejectedByDiameterTrackMask = false(numberOfTracks,1);
fragmentRejectedByMeasurementResolutionTrackMask = ...
    false(numberOfTracks,1);
mergedTracks = tracks([]);

if numberOfTracks == 0
    return;
end

positions = reshape([tracks.position], 2, [])';
clusterCount = 0;

for seedIndex = 1:numberOfTracks

    if clusterIndex(seedIndex) > 0
        continue;
    end

    clusterCount = clusterCount + 1;
    clusterIndex(seedIndex) = clusterCount;
    clusterMembers = seedIndex;

    while true

        candidateIndices = find(clusterIndex == 0);
        bestCandidateIndex = 0;
        bestLinkDistance = inf;

        for candidateIndex = candidateIndices(:)'
            memberOffsets = ...
                positions(clusterMembers,:) - ...
                positions(candidateIndex,:);
            memberDistances = hypot( ...
                memberOffsets(:,1), ...
                memberOffsets(:,2));
            [euclideanDistance, nearestMemberOffset] = ...
                min(memberDistances);
            currentIndex = ...
                clusterMembers(nearestMemberOffset);

            isInsideFixedGate = ...
                euclideanDistance <= mergeDistance;
            isInsideUncertaintyGate = false;

            if ~isInsideFixedGate && ...
                    euclideanDistance <= maximumEdgeDistance
                mahalanobisDistance = ...
                    calculateTrackMahalanobisDistance( ...
                        tracks(currentIndex), ...
                        tracks(candidateIndex));
                isInsideUncertaintyGate = ...
                    mahalanobisDistance <= ...
                    maximumMahalanobisDistance;
            end

            proposedDiameter = max(memberDistances);
            preservesClusterDiameter = ...
                proposedDiameter <= maximumClusterDiameter;

            if (isInsideFixedGate || ...
                    isInsideUncertaintyGate) && ...
                    preservesClusterDiameter && ...
                    euclideanDistance < bestLinkDistance
                bestCandidateIndex = candidateIndex;
                bestLinkDistance = euclideanDistance;
            end
        end

        if bestCandidateIndex == 0
            break;
        end

        clusterIndex(bestCandidateIndex) = clusterCount;
        clusterMembers(end+1,1) = ... %#ok<AGROW>
            bestCandidateIndex;

    end

end


compactClusterIndex = clusterIndex;

for currentCluster = 1:clusterCount
    groupPositions = positions( ...
        compactClusterIndex == currentCluster,:);
    compactClusterDiameters(currentCluster,1) = ... %#ok<AGROW>
        calculatePositionDiameter(groupPositions);
end

[clusterIndex, absorbedFragmentTrackMask, ...
        fragmentTargetCompactClusterIndex, ...
        fragmentRejectedByDiameterTrackMask, ...
        fragmentRejectedByMeasurementResolutionTrackMask] = ...
    reconcileSingletonTrackFragments( ...
        tracks, ...
        compactClusterIndex, ...
        fragmentAssociationDistance, ...
        fragmentAssociationAmbiguityMargin, ...
        fragmentMinimumCoreMembers, ...
        maximumClusterDiameter, ...
        minimumIndependentViewDistance, ...
        minimumResolvedRangedViews, ...
        resolvedSourceMinimumSeparation);

finalClusterIDs = unique(clusterIndex, 'stable');
renumberedClusterIndex = zeros(size(clusterIndex));

for finalCluster = 1:numel(finalClusterIDs)
    renumberedClusterIndex( ...
        clusterIndex == finalClusterIDs(finalCluster)) = ...
        finalCluster;
end

clusterIndex = renumberedClusterIndex;
clusterCount = numel(finalClusterIDs);


for currentCluster = 1:clusterCount
    group = tracks(clusterIndex == currentCluster);
    groupPositions = reshape([group.position], 2, [])';
    clusterDiameters(currentCluster,1) = ... %#ok<AGROW>
        calculatePositionDiameter(groupPositions);
    mergedTracks(end+1,1) = mergeTrackGroup( ... %#ok<AGROW>
        group, minimumIndependentViewDistance);
end

end


function [reconciledClusterIndex, absorbedTrackMask, ...
        fragmentTargetCompactClusterIndex, ...
        rejectedByDiameterTrackMask, ...
        rejectedByMeasurementResolutionTrackMask] = ...
    reconcileSingletonTrackFragments( ...
        tracks, ...
        compactClusterIndex, ...
        maximumFragmentDistance, ...
        ambiguityMargin, ...
        minimumCoreMembers, ...
        maximumClusterDiameter, ...
        minimumIndependentViewDistance, ...
        minimumResolvedRangedViews, ...
        resolvedSourceMinimumSeparation)
% تعيد عنقودًا منفردًا إلى أقرب عنقود مدمج ومدعوم فقط. تستخدم
% مراكز العناقيد المدمجة الأصلية مرة واحدة، ولذلك لا تستطيع الشظية
% الممتصة أن تعمل كحلقة جديدة في سلسلة اتصال بين ضحيتين. كما أن
% كل امتصاص يجب أن يحافظ على حد القطر التراكمي للعنقود؛ فلا يجوز
% لشظيتين مقبولتين منفردتين أن تمددا النواة من طرفين مختلفين.

reconciledClusterIndex = compactClusterIndex;
absorbedTrackMask = false(numel(tracks),1);
fragmentTargetCompactClusterIndex = ...
    zeros(numel(tracks),1);
rejectedByDiameterTrackMask = false(numel(tracks),1);
rejectedByMeasurementResolutionTrackMask = ...
    false(numel(tracks),1);

if maximumFragmentDistance <= 0 || isempty(tracks)
    return;
end

compactClusterIDs = unique(compactClusterIndex, 'stable');
numberOfCompactClusters = numel(compactClusterIDs);
compactClusterCounts = zeros(numberOfCompactClusters,1);
compactRepresentatives = zeros(numberOfCompactClusters,2);

for compactOffset = 1:numberOfCompactClusters
    compactClusterID = compactClusterIDs(compactOffset);
    memberMask = compactClusterIndex == compactClusterID;
    compactClusterCounts(compactOffset) = nnz(memberMask);
    compactTrack = mergeTrackGroup( ...
        tracks(memberMask), ...
        minimumIndependentViewDistance);
    compactRepresentatives(compactOffset,:) = ...
        compactTrack.position(1:2);
end

coreOffsets = find( ...
    compactClusterCounts >= minimumCoreMembers);

if isempty(coreOffsets)
    return;
end

fragmentOffsets = find(compactClusterCounts == 1);

for fragmentOffset = fragmentOffsets(:)'
    fragmentClusterID = ...
        compactClusterIDs(fragmentOffset);
    fragmentPosition = ...
        compactRepresentatives(fragmentOffset,:);
    coreOffsetsFromFragment = ...
        compactRepresentatives(coreOffsets,:) - ...
        fragmentPosition;
    coreDistances = hypot( ...
        coreOffsetsFromFragment(:,1), ...
        coreOffsetsFromFragment(:,2));
    [sortedDistances, sortedOffsets] = ...
        sort(coreDistances, 'ascend');

    nearestDistance = sortedDistances(1);
    hasUniqueTarget = numel(sortedDistances) == 1 || ...
        sortedDistances(2) - nearestDistance >= ...
        ambiguityMargin;

    if nearestDistance > maximumFragmentDistance || ...
            ~hasUniqueTarget
        continue;
    end

    targetCoreOffset = ...
        coreOffsets(sortedOffsets(1));
    targetCompactClusterID = ...
        compactClusterIDs(targetCoreOffset);
    fragmentTrackMask = ...
        compactClusterIndex == fragmentClusterID;
    targetTrackMask = ...
        reconciledClusterIndex == targetCompactClusterID;
    proposedTrackMask = ...
        targetTrackMask | fragmentTrackMask;
    proposedPositions = reshape( ...
        [tracks(proposedTrackMask).position],2,[])';
    proposedDiameter = ...
        calculatePositionDiameter(proposedPositions);

    fragmentTrack = tracks(fragmentTrackMask);
    targetTracks = tracks(targetTrackMask);
    fragmentIsResolved = ...
        fragmentTrack.independentRangedViewCount >= ...
        minimumResolvedRangedViews;
    targetIsResolved = any( ...
        [targetTracks.independentRangedViewCount] >= ...
        minimumResolvedRangedViews);
    preservesResolvedSources = ~( ...
        fragmentIsResolved && targetIsResolved && ...
        nearestDistance >= ...
            resolvedSourceMinimumSeparation);

    if ~preservesResolvedSources
        rejectedByMeasurementResolutionTrackMask( ...
            fragmentTrackMask) = true;
        continue;
    end

    if proposedDiameter > maximumClusterDiameter
        rejectedByDiameterTrackMask(fragmentTrackMask) = true;
        continue;
    end

    reconciledClusterIndex(fragmentTrackMask) = ...
        targetCompactClusterID;
    absorbedTrackMask(fragmentTrackMask) = true;
    fragmentTargetCompactClusterIndex(fragmentTrackMask) = ...
        targetCompactClusterID;
end

end


function diagnostics = createEmptyBasinDiagnostics( ...
    numberOfClusters)

diagnostics = struct();
diagnostics.peakPositions = zeros(numberOfClusters,2);
diagnostics.peakLogOdds = -inf(numberOfClusters,1);
diagnostics.peakSupport = zeros(numberOfClusters,1);
diagnostics.pairwisePeakDistances = ...
    inf(numberOfClusters,numberOfClusters);
diagnostics.pairwiseValleyDrops = ...
    inf(numberOfClusters,numberOfClusters);
diagnostics.pairwiseSupportRetention = ...
    zeros(numberOfClusters,numberOfClusters);
diagnostics.pairwiseTemporalContainment = ...
    zeros(numberOfClusters,numberOfClusters);
diagnostics.pairwiseTemporalJaccard = ...
    zeros(numberOfClusters,numberOfClusters);
diagnostics.independentRangedViewCounts = ...
    zeros(numberOfClusters,1);
diagnostics.pairwiseMeasurementResolvedVeto = ...
    false(numberOfClusters,numberOfClusters);
diagnostics.preToFinalClusterIndex = ...
    (1:numberOfClusters)';
diagnostics.mergedClusterCount = 0;
diagnostics.rejectedPreClusterMask = ...
    false(numberOfClusters,1);
diagnostics.rejectedClusterCount = 0;

if numberOfClusters > 0
    diagnostics.pairwisePeakDistances( ...
        1:numberOfClusters+1:end) = 0;
    diagnostics.pairwiseValleyDrops( ...
        1:numberOfClusters+1:end) = 0;
    diagnostics.pairwiseSupportRetention( ...
        1:numberOfClusters+1:end) = 1;
    diagnostics.pairwiseTemporalContainment( ...
        1:numberOfClusters+1:end) = 1;
    diagnostics.pairwiseTemporalJaccard( ...
        1:numberOfClusters+1:end) = 1;
end

end


function [mergedTracks, finalRawClusterIndex, ...
        finalClusterDiameters, diagnostics] = ...
    consolidateTrackClustersByLogOddsBasins( ...
        rawTracks, ...
        preBasinMergedTracks, ...
        rawPreBasinClusterIndex, ...
        logOddsMap, ...
        weightedSupportMap, ...
        maximumValleyDrop, ...
        maximumPeakDistance, ...
        peakSearchRadius, ...
        minimumPeakLogOdds, ...
        lineSamplesPerCell, ...
        minimumSupportRetention, ...
        weakMinimumLogOddsGap, ...
        weakMaximumRelativeSupport, ...
        weakMaximumRawTracks, ...
        weakMapMinimumLogOddsGap, ...
        weakMapMaximumRelativeSupport, ...
        weakMapMaximumRawTracks, ...
        minimumIndependentViewDistance, ...
        minimumResolvedRangedViews, ...
        resolvedSourceMinimumSeparation, ...
        resolvedSourceSoftPeakSeparation, ...
        resolvedSourceMaximumBridgeRetention)
% يدمج فقط العناقيد التي تقع جميع أزواج قممها داخل حوض Log-Odds
% واحد. قاعدة complete-link تمنع سلسلة من العلاقات المحلية من
% دمج مجموعتين يفصل بينهما وادٍ قوي أو مسافة غير مسموحة.

numberOfPreBasinClusters = ...
    numel(preBasinMergedTracks);
diagnostics = createEmptyBasinDiagnostics( ...
    numberOfPreBasinClusters);
mergedTracks = preBasinMergedTracks;
finalRawClusterIndex = rawPreBasinClusterIndex;
finalClusterDiameters = zeros( ...
    numberOfPreBasinClusters,1);

for clusterIndex = 1:numberOfPreBasinClusters
    groupPositions = reshape( ...
        [rawTracks( ...
        rawPreBasinClusterIndex == clusterIndex).position], ...
        2,[])';
    finalClusterDiameters(clusterIndex) = ...
        calculatePositionDiameter(groupPositions);
end

clusterUpdateSteps = cell(numberOfPreBasinClusters,1);

for clusterIndex = 1:numberOfPreBasinClusters
    clusterMembers = rawTracks( ...
        rawPreBasinClusterIndex == clusterIndex);
    updateSteps = zeros(0,1);

    for memberIndex = 1:numel(clusterMembers)
        if isfield(clusterMembers, 'updateStepHistory') && ...
                ~isempty(clusterMembers(memberIndex).updateStepHistory)
            updateSteps = [ ...
                updateSteps; ...
                clusterMembers(memberIndex).updateStepHistory(:)]; ...
                %#ok<AGROW>
        elseif isfield(clusterMembers, 'lastUpdateStep') && ...
                ~isempty(clusterMembers(memberIndex).lastUpdateStep)
            updateSteps(end+1,1) = ... %#ok<AGROW>
                clusterMembers(memberIndex).lastUpdateStep;
        end
    end

    clusterUpdateSteps{clusterIndex} = unique(updateSteps);
    diagnostics.independentRangedViewCounts(clusterIndex) = ...
        max([clusterMembers.independentRangedViewCount]);
end

if isempty(logOddsMap) || ...
        ~isequal(size(logOddsMap), ...
        size(weightedSupportMap))
    return;
end

for clusterIndex = 1:numberOfPreBasinClusters
    [peakPosition,peakValue] = ...
        findStrongestLocalLogOddsPeak( ...
            logOddsMap, ...
            preBasinMergedTracks(clusterIndex).position, ...
            peakSearchRadius);
    diagnostics.peakPositions(clusterIndex,:) = ...
        peakPosition;
    diagnostics.peakLogOdds(clusterIndex) = ...
        peakValue;
    diagnostics.peakSupport(clusterIndex) = ...
        weightedSupportMap( ...
            peakPosition(1),peakPosition(2));
end


if numberOfPreBasinClusters < 2 || ...
        maximumValleyDrop < 0
    return;
end

for firstCluster = 1:numberOfPreBasinClusters
    for secondCluster = ...
            firstCluster+1:numberOfPreBasinClusters
        firstPeakPosition = ...
            diagnostics.peakPositions(firstCluster,:);
        secondPeakPosition = ...
            diagnostics.peakPositions(secondCluster,:);
        peakDistance = norm( ...
            firstPeakPosition-secondPeakPosition);
        valleyDrop = calculateLogOddsValleyDrop( ...
            logOddsMap, ...
            firstPeakPosition, ...
            secondPeakPosition, ...
            diagnostics.peakLogOdds(firstCluster), ...
            diagnostics.peakLogOdds(secondCluster), ...
            lineSamplesPerCell);
        supportRetention = ...
            calculateSupportRetention( ...
                weightedSupportMap, ...
                firstPeakPosition, ...
                secondPeakPosition, ...
                diagnostics.peakSupport(firstCluster), ...
                diagnostics.peakSupport(secondCluster), ...
                lineSamplesPerCell);
        hasResolvedRangedEvidence = ...
            diagnostics.independentRangedViewCounts( ...
                firstCluster) >= minimumResolvedRangedViews && ...
            diagnostics.independentRangedViewCounts( ...
                secondCluster) >= minimumResolvedRangedViews;
        hasHardPeakSeparation = ...
            peakDistance >= resolvedSourceMinimumSeparation;
        hasSoftPeakSeparationWithSupportValley = ...
            peakDistance >= resolvedSourceSoftPeakSeparation && ...
            supportRetention <= ...
                resolvedSourceMaximumBridgeRetention;
        measurementResolvedVeto = ...
            hasResolvedRangedEvidence && ...
            (hasHardPeakSeparation || ...
             hasSoftPeakSeparationWithSupportValley);
        firstUpdateSteps = ...
            clusterUpdateSteps{firstCluster};
        secondUpdateSteps = ...
            clusterUpdateSteps{secondCluster};
        sharedUpdateStepCount = numel(intersect( ...
            firstUpdateSteps,secondUpdateSteps));
        minimumUpdateStepCount = min( ...
            numel(firstUpdateSteps), ...
            numel(secondUpdateSteps));
        unionUpdateStepCount = numel(union( ...
            firstUpdateSteps,secondUpdateSteps));

        if minimumUpdateStepCount > 0
            temporalContainment = ...
                sharedUpdateStepCount / ...
                minimumUpdateStepCount;
        else
            temporalContainment = 0;
        end

        if unionUpdateStepCount > 0
            temporalJaccard = ...
                sharedUpdateStepCount / ...
                unionUpdateStepCount;
        else
            temporalJaccard = 0;
        end
        diagnostics.pairwisePeakDistances( ...
            firstCluster,secondCluster) = peakDistance;
        diagnostics.pairwisePeakDistances( ...
            secondCluster,firstCluster) = peakDistance;
        diagnostics.pairwiseValleyDrops( ...
            firstCluster,secondCluster) = valleyDrop;
        diagnostics.pairwiseValleyDrops( ...
            secondCluster,firstCluster) = valleyDrop;
        diagnostics.pairwiseSupportRetention( ...
            firstCluster,secondCluster) = ...
            supportRetention;
        diagnostics.pairwiseSupportRetention( ...
            secondCluster,firstCluster) = ...
            supportRetention;
        diagnostics.pairwiseTemporalContainment( ...
            firstCluster,secondCluster) = ...
            temporalContainment;
        diagnostics.pairwiseTemporalContainment( ...
            secondCluster,firstCluster) = ...
            temporalContainment;
        diagnostics.pairwiseTemporalJaccard( ...
            firstCluster,secondCluster) = ...
            temporalJaccard;
        diagnostics.pairwiseTemporalJaccard( ...
            secondCluster,firstCluster) = ...
            temporalJaccard;
        diagnostics.pairwiseMeasurementResolvedVeto( ...
            firstCluster,secondCluster) = ...
            measurementResolvedVeto;
        diagnostics.pairwiseMeasurementResolvedVeto( ...
            secondCluster,firstCluster) = ...
            measurementResolvedVeto;
    end
end

groupIndex = (1:numberOfPreBasinClusters)';

while true
    groupIDs = unique(groupIndex, 'stable');
    bestFirstGroupID = 0;
    bestSecondGroupID = 0;
    bestMaximumValleyDrop = inf;
    bestMaximumPeakDistance = inf;

    for firstOffset = 1:numel(groupIDs)
        firstGroupID = groupIDs(firstOffset);
        firstMembers = find( ...
            groupIndex == firstGroupID);

        for secondOffset = ...
                firstOffset+1:numel(groupIDs)
            secondGroupID = groupIDs(secondOffset);
            secondMembers = find( ...
                groupIndex == secondGroupID);
            crossValleyDrops = ...
                diagnostics.pairwiseValleyDrops( ...
                    firstMembers,secondMembers);
            crossPeakDistances = ...
                diagnostics.pairwisePeakDistances( ...
                    firstMembers,secondMembers);
            crossSupportRetention = ...
                diagnostics.pairwiseSupportRetention( ...
                    firstMembers,secondMembers);
            crossMeasurementResolvedVeto = ...
                diagnostics.pairwiseMeasurementResolvedVeto( ...
                    firstMembers,secondMembers);
            allMembers = [ ...
                firstMembers; secondMembers];
            peaksAreStrong = all( ...
                diagnostics.peakLogOdds(allMembers) >= ...
                minimumPeakLogOdds);
            groupsShareOneBasin = ...
                peaksAreStrong && ...
                all(crossValleyDrops(:) <= ...
                    maximumValleyDrop) && ...
                all(crossPeakDistances(:) <= ...
                    maximumPeakDistance) && ...
                all(crossSupportRetention(:) >= ...
                    minimumSupportRetention) && ...
                ~any(crossMeasurementResolvedVeto(:));

            if ~groupsShareOneBasin
                continue;
            end

            candidateMaximumValleyDrop = ...
                max(crossValleyDrops(:));
            candidateMaximumPeakDistance = ...
                max(crossPeakDistances(:));
            isBetterCandidate = ...
                candidateMaximumValleyDrop < ...
                    bestMaximumValleyDrop || ...
                (candidateMaximumValleyDrop == ...
                    bestMaximumValleyDrop && ...
                candidateMaximumPeakDistance < ...
                    bestMaximumPeakDistance);

            if isBetterCandidate
                bestFirstGroupID = firstGroupID;
                bestSecondGroupID = secondGroupID;
                bestMaximumValleyDrop = ...
                    candidateMaximumValleyDrop;
                bestMaximumPeakDistance = ...
                    candidateMaximumPeakDistance;
            end
        end
    end

    if bestFirstGroupID == 0
        break;
    end

    groupIndex(groupIndex == bestSecondGroupID) = ...
        bestFirstGroupID;
end

groupIDs = unique(groupIndex, 'stable');
provisionalPreToFinalClusterIndex = ...
    zeros(size(groupIndex));

for provisionalCluster = 1:numel(groupIDs)
    provisionalPreToFinalClusterIndex( ...
        groupIndex == groupIDs(provisionalCluster)) = ...
        provisionalCluster;
end

% تصفية مشتركة شديدة المحافظة للحوض المنفرد الضعيف. لا تكفي
% أي إشارة منفردة: يجب أن يدعمه مسار خام واحد فقط، وأن يكون فرق
% Log-Odds كبيرًا، وأن يكون دعمه النسبي منخفضًا، مع وجود حوض آخر.
numberOfProvisionalClusters = numel(groupIDs);
rawProvisionalClusterIndex = ...
    provisionalPreToFinalClusterIndex( ...
        rawPreBasinClusterIndex);
provisionalPeakLogOdds = ...
    -inf(numberOfProvisionalClusters,1);
provisionalPeakSupport = ...
    zeros(numberOfProvisionalClusters,1);
provisionalRawTrackCounts = ...
    zeros(numberOfProvisionalClusters,1);
provisionalMeasurementResolved = ...
    false(numberOfProvisionalClusters,1);

for provisionalCluster = ...
        1:numberOfProvisionalClusters
    preMembers = find( ...
        provisionalPreToFinalClusterIndex == ...
        provisionalCluster);
    provisionalPeakLogOdds(provisionalCluster) = ...
        max(diagnostics.peakLogOdds(preMembers));
    provisionalPeakSupport(provisionalCluster) = ...
        max(diagnostics.peakSupport(preMembers));
    provisionalRawTrackCounts(provisionalCluster) = ...
        nnz(rawProvisionalClusterIndex == ...
        provisionalCluster);
    provisionalMeasurementResolved(provisionalCluster) = ...
        any(diagnostics.independentRangedViewCounts( ...
            preMembers) >= minimumResolvedRangedViews);
end

rejectedProvisionalClusterMask = ...
    false(numberOfProvisionalClusters,1);

if numberOfProvisionalClusters > 1
    strongestPeakLogOdds = ...
        max(provisionalPeakLogOdds);
    strongestPeakSupport = ...
        max(provisionalPeakSupport);

    for provisionalCluster = ...
            1:numberOfProvisionalClusters
        logOddsGap = strongestPeakLogOdds - ...
            provisionalPeakLogOdds(provisionalCluster);
        relativeSupport = ...
            provisionalPeakSupport(provisionalCluster) / ...
            max(strongestPeakSupport,eps);
        isWeakSingleton = ...
            provisionalRawTrackCounts( ...
                provisionalCluster) <= ...
                weakMaximumRawTracks && ...
            logOddsGap >= weakMinimumLogOddsGap && ...
            relativeSupport <= ...
                weakMaximumRelativeSupport;
        isWeakMapOnlyPair = ...
            provisionalRawTrackCounts( ...
                provisionalCluster) <= ...
                weakMapMaximumRawTracks && ...
            logOddsGap >= weakMapMinimumLogOddsGap && ...
            relativeSupport <= ...
                weakMapMaximumRelativeSupport;
        rejectedProvisionalClusterMask( ...
            provisionalCluster) = ...
            ~provisionalMeasurementResolved( ...
                provisionalCluster) && ...
            (isWeakSingleton || isWeakMapOnlyPair);
    end
end

preToFinalClusterIndex = zeros(size(groupIndex));
acceptedProvisionalClusters = find( ...
    ~rejectedProvisionalClusterMask);

for finalCluster = ...
        1:numel(acceptedProvisionalClusters)
    provisionalCluster = ...
        acceptedProvisionalClusters(finalCluster);
    preToFinalClusterIndex( ...
        provisionalPreToFinalClusterIndex == ...
        provisionalCluster) = finalCluster;
end

diagnostics.preToFinalClusterIndex = ...
    preToFinalClusterIndex;
diagnostics.mergedClusterCount = ...
    numberOfPreBasinClusters-numel(groupIDs);
diagnostics.rejectedPreClusterMask = ...
    rejectedProvisionalClusterMask( ...
        provisionalPreToFinalClusterIndex);
diagnostics.rejectedClusterCount = ...
    nnz(rejectedProvisionalClusterMask);
finalRawClusterIndex = ...
    preToFinalClusterIndex( ...
        rawPreBasinClusterIndex);
mergedTracks = rawTracks([]);
numberOfFinalClusters = ...
    numel(acceptedProvisionalClusters);
finalClusterDiameters = zeros( ...
    numberOfFinalClusters,1);

for finalCluster = 1:numberOfFinalClusters
    group = rawTracks( ...
        finalRawClusterIndex == finalCluster);
    groupPositions = reshape( ...
        [group.position],2,[])';
    finalClusterDiameters(finalCluster) = ...
        calculatePositionDiameter(groupPositions);
    mergedTracks(end+1,1) = mergeTrackGroup( ... %#ok<AGROW>
        group,minimumIndependentViewDistance);
end

end


function [peakPosition,peakValue] = ...
    findStrongestLocalLogOddsPeak( ...
        logOddsMap,trackPosition,searchRadius)

centerRow = min(max( ...
    1,round(trackPosition(1))), ...
    size(logOddsMap,1));
centerColumn = min(max( ...
    1,round(trackPosition(2))), ...
    size(logOddsMap,2));
minimumRow = max(1,centerRow-searchRadius);
maximumRow = min( ...
    size(logOddsMap,1),centerRow+searchRadius);
minimumColumn = max(1,centerColumn-searchRadius);
maximumColumn = min( ...
    size(logOddsMap,2),centerColumn+searchRadius);
localMap = logOddsMap( ...
    minimumRow:maximumRow, ...
    minimumColumn:maximumColumn);
[peakValue,localIndex] = max(localMap(:));
[localRow,localColumn] = ...
    ind2sub(size(localMap),localIndex);
peakPosition = [ ...
    minimumRow+localRow-1, ...
    minimumColumn+localColumn-1];

end


function valleyDrop = calculateLogOddsValleyDrop( ...
    logOddsMap,firstPeakPosition,secondPeakPosition, ...
    firstPeakValue,secondPeakValue,lineSamplesPerCell)

peakDistance = norm( ...
    firstPeakPosition-secondPeakPosition);
sampleCount = max( ...
    3,ceil(peakDistance*lineSamplesPerCell)+1);
sampleRows = linspace( ...
    firstPeakPosition(1), ...
    secondPeakPosition(1), ...
    sampleCount);
sampleColumns = linspace( ...
    firstPeakPosition(2), ...
    secondPeakPosition(2), ...
    sampleCount);
lineLogOdds = interp2( ...
    logOddsMap,sampleColumns,sampleRows,'linear');

if any(~isfinite(lineLogOdds))
    valleyDrop = inf;
    return;
end

lowerPeakValue = min( ...
    firstPeakValue,secondPeakValue);
valleyDrop = max( ...
    0,lowerPeakValue-min(lineLogOdds));

end


function retention = calculateSupportRetention( ...
    supportMap,firstPeakPosition,secondPeakPosition, ...
    firstPeakSupport,secondPeakSupport,lineSamplesPerCell)

peakDistance = norm( ...
    firstPeakPosition-secondPeakPosition);
sampleCount = max( ...
    3,ceil(peakDistance*lineSamplesPerCell)+1);
sampleRows = linspace( ...
    firstPeakPosition(1), ...
    secondPeakPosition(1), ...
    sampleCount);
sampleColumns = linspace( ...
    firstPeakPosition(2), ...
    secondPeakPosition(2), ...
    sampleCount);
lineSupport = interp2( ...
    supportMap,sampleColumns,sampleRows,'linear');

if any(~isfinite(lineSupport))
    retention = 0;
    return;
end

lowerPeakSupport = min( ...
    firstPeakSupport,secondPeakSupport);

if lowerPeakSupport <= eps
    retention = 0;
    return;
end

retention = min( ...
    1,max(0,min(lineSupport) / ...
    lowerPeakSupport));

end


function diameter = calculatePositionDiameter(positions)

if size(positions,1) < 2
    diameter = 0;
    return;
end

rowOffsets = positions(:,1) - positions(:,1)';
columnOffsets = positions(:,2) - positions(:,2)';
distances = hypot(rowOffsets, columnOffsets);
diameter = max(distances(:));

end


function distance = calculateTrackMahalanobisDistance( ...
    firstTrack, ...
    secondTrack)

positionOffset = ...
    firstTrack.position(1:2)' - ...
    secondTrack.position(1:2)';
combinedCovariance = ...
    firstTrack.covariance + ...
    secondTrack.covariance;

if ~isequal(size(combinedCovariance), [2 2]) || ...
        any(~isfinite(combinedCovariance), 'all')
    distance = inf;
    return;
end

combinedCovariance = ...
    0.5 * (combinedCovariance + combinedCovariance');
combinedCovariance = ...
    combinedCovariance + 1e-9 * eye(2);

squaredDistance = ...
    positionOffset' * ...
    pinv(combinedCovariance) * ...
    positionOffset;
distance = sqrt(max(0, squaredDistance));

end


function mergedTrack = mergeTrackGroup( ...
    tracks, minimumIndependentViewDistance)

if numel(tracks) == 1
    mergedTrack = tracks;
    return;
end

existenceProbabilities = ...
    [tracks.existenceProbability]';
independentViewCounts = ...
    [tracks.independentViewCount]';
weights = max(eps, existenceProbabilities) .* ...
    max(1, independentViewCounts);
positions = reshape([tracks.position], 2, [])';
mergedPosition = sum(positions .* weights, 1) ./ ...
    sum(weights);

mergedCovariance = zeros(2,2);
for index = 1:numel(tracks)
    offset = positions(index,:) - mergedPosition;
    mergedCovariance = mergedCovariance + ...
        weights(index) .* ( ...
            tracks(index).covariance + ...
            offset(:) * offset(:)');
end
mergedCovariance = mergedCovariance ./ sum(weights);

[~, baseIndex] = max(independentViewCounts);
mergedTrack = tracks(baseIndex);
mergedTrack.id = min([tracks.id]);
mergedTrack.position = mergedPosition;
mergedTrack.existenceProbability = ...
    max(existenceProbabilities);
mergedTrack.covariance = mergedCovariance;
mergedTrack.updateCount = max([tracks.updateCount]);
mergedTrack.maximumProbability = ...
    max([tracks.maximumProbability]);
mergedTrack.missedUpdateCount = ...
    min([tracks.missedUpdateCount]);
mergedTrack.lastUpdateStep = ...
    max([tracks.lastUpdateStep]);
mergedUpdateSteps = zeros(0,1);

for trackIndex = 1:numel(tracks)
    if isfield(tracks, 'updateStepHistory') && ...
            ~isempty(tracks(trackIndex).updateStepHistory)
        mergedUpdateSteps = [ ...
            mergedUpdateSteps; ...
            tracks(trackIndex).updateStepHistory(:)]; ...
            %#ok<AGROW>
    elseif ~isempty(tracks(trackIndex).lastUpdateStep)
        mergedUpdateSteps(end+1,1) = ... %#ok<AGROW>
            tracks(trackIndex).lastUpdateStep;
    end
end

mergedTrack.updateStepHistory = ...
    unique(mergedUpdateSteps);
mergedTrack.rangedMeasurementUpdateCount = ...
    max([tracks.rangedMeasurementUpdateCount]);

mergedObservations = ...
    tracks(baseIndex).observationPositions(:,1:2);
for trackIndex = 1:numel(tracks)
    observations = tracks(trackIndex).observationPositions;
    for observationIndex = 1:size(observations,1)
        candidate = observations(observationIndex,1:2);
        if isempty(mergedObservations)
            mergedObservations = candidate;
        else
            distances = hypot( ...
                mergedObservations(:,1) - candidate(1), ...
                mergedObservations(:,2) - candidate(2));
            if all(distances >= minimumIndependentViewDistance)
                mergedObservations(end+1,:) = ... %#ok<AGROW>
                    candidate;
            end
        end
    end
end

mergedTrack.observationPositions = mergedObservations;
mergedTrack.independentViewCount = ...
    size(mergedObservations,1);

mergedRangedObservations = zeros(0,2);
for trackIndex = 1:numel(tracks)
    rangedObservations = ...
        tracks(trackIndex).rangedObservationPositions;
    for observationIndex = 1:size(rangedObservations,1)
        candidate = rangedObservations(observationIndex,1:2);
        if isempty(mergedRangedObservations)
            mergedRangedObservations = candidate;
        else
            distances = hypot( ...
                mergedRangedObservations(:,1)-candidate(1), ...
                mergedRangedObservations(:,2)-candidate(2));
            if all(distances >= minimumIndependentViewDistance)
                mergedRangedObservations(end+1,:) = ... %#ok<AGROW>
                    candidate;
            end
        end
    end
end

mergedTrack.rangedObservationPositions = ...
    mergedRangedObservations;
mergedTrack.independentRangedViewCount = ...
    size(mergedRangedObservations,1);
mergedTrack.status = "CONFIRMED";

end


function tracks = normalizeMeasurementResolvedTrackSchema(tracks)

for trackIndex = 1:numel(tracks)
    if ~isfield(tracks,'rangedMeasurementUpdateCount') || ...
            isempty(tracks(trackIndex).rangedMeasurementUpdateCount)
        tracks(trackIndex).rangedMeasurementUpdateCount = 0;
    end
    if ~isfield(tracks,'independentRangedViewCount') || ...
            isempty(tracks(trackIndex).independentRangedViewCount)
        tracks(trackIndex).independentRangedViewCount = 0;
    end
    if ~isfield(tracks,'rangedObservationPositions') || ...
            isempty(tracks(trackIndex).rangedObservationPositions)
        tracks(trackIndex).rangedObservationPositions = zeros(0,2);
    end
end

end
