function [peaks, state] = detectBayesianPosteriorPeaks(state)
%% ============================================================
% استخراج قمم posterior موثوقة بعتبة تكيفية وNMS مكاني.
%% ============================================================

config = constants();
bayesianConfig = readLocalizationConfig(state, config);
peaks = emptyPeakArray();

currentEvidenceMask = true(state.gridSize);
isSpatialState = ...
    isfield(state, 'localizationMethod') && ...
    lower(string(state.localizationMethod)) == ...
        "spatialbayesianfusion";

if isSpatialState
    requiredEvidenceFields = { ...
        'lastMeasurementLogBayesFactorMap', ...
        'lastVisibilityMask'};

    if ~all(isfield(state, requiredEvidenceFields))
        currentEvidenceMask(:) = false;
    else
        minimumCurrentEvidence = ...
            bayesianConfig.minimumCurrentPeakLogBayesFactor;
        currentEvidenceMask = ...
            state.lastVisibilityMask & ...
            isfinite( ...
                state.lastMeasurementLogBayesFactorMap) & ...
            state.lastMeasurementLogBayesFactorMap >= ...
                minimumCurrentEvidence;
    end
end

supportMask = ...
    state.observationCount >= ...
    bayesianConfig.minimumObservationCount & ...
    state.lastObservationStep == state.updateCount & ...
    isfinite(state.probabilityMap) & ...
    currentEvidenceMask;
% في المسار المكاني لا تكفي رؤية الخلية في هذه الخطوة؛ يجب أن يحمل
% القياس الحالي نفسه دليلًا موجبًا. وبذلك لا يعاد احتساب posterior قديم
% كمشاهدة مستقلة جديدة من موقع مسبار مختلف.

backgroundValues = state.probabilityMap(supportMask);

if isempty(backgroundValues)
    state.lastAdaptiveThreshold = ...
        bayesianConfig.minimumPosteriorProbability;
    state.lastBackgroundMedian = NaN;
    state.lastBackgroundRobustSigma = NaN;
    state.lastCandidatePeakCount = 0;
    state.lastPeaks = peaks;
    return;
end

backgroundMedian = median(backgroundValues);
backgroundMad = median(abs( ...
    backgroundValues - backgroundMedian));
backgroundRobustSigma = 1.4826 * backgroundMad;

adaptiveThreshold = max( ...
    bayesianConfig.minimumPosteriorProbability, ...
    backgroundMedian + ...
    bayesianConfig.backgroundSigmaMultiplier * ...
        backgroundRobustSigma);
adaptiveThreshold = min(1 - eps, adaptiveThreshold);

candidatePeaks = emptyPeakArray();
radius = bayesianConfig.localMaximumRadius;
numberOfRows = state.gridSize(1);
numberOfColumns = state.gridSize(2);
useLogOddsContrast = isSpatialState && ...
    isfield(bayesianConfig, ...
        'minimumLogOddsPeakProminence');

if useLogOddsContrast
    minimumContrastProminence = ...
        bayesianConfig.minimumLogOddsPeakProminence;
    minimumPlateauSupportProminence = ...
        bayesianConfig.minimumPlateauSupportProminence;
    contrastMap = state.logOddsMap;
else
    minimumContrastProminence = ...
        bayesianConfig.minimumPeakProminence;
    minimumPlateauSupportProminence = Inf;
    contrastMap = state.probabilityMap;
end

for rowIndex = 1:numberOfRows
    for columnIndex = 1:numberOfColumns

        if ~supportMask(rowIndex, columnIndex)
            continue;
        end

        probability = state.probabilityMap(rowIndex, columnIndex);
        if probability < adaptiveThreshold
            continue;
        end

        rowRange = max(1, rowIndex-radius): ...
            min(numberOfRows, rowIndex+radius);
        columnRange = max(1, columnIndex-radius): ...
            min(numberOfColumns, columnIndex+radius);

        contrastNeighborhood = contrastMap( ...
            rowRange, columnRange);
        currentContrast = contrastMap( ...
            rowIndex, columnIndex);
        localRow = rowIndex - rowRange(1) + 1;
        localColumn = columnIndex - columnRange(1) + 1;
        neighborMask = true(size(contrastNeighborhood));
        neighborMask(localRow, localColumn) = false;
        neighborValues = ...
            contrastNeighborhood(neighborMask);

        if isempty(neighborValues)
            prominence = currentContrast;
        else
            maximumNeighbor = max(neighborValues);
            tolerance = max( ...
                1e-12, ...
                eps(max(1, abs(currentContrast))));

            if currentContrast < ...
                    maximumNeighbor - tolerance
                continue;
            end

            prominence = currentContrast - ...
                median(neighborValues);

            if abs(currentContrast - maximumNeighbor) <= ...
                    tolerance
                localSupport = state.weightedObservationSupport( ...
                    rowRange, columnRange);
                neighborSupport = localSupport(neighborMask & ...
                    abs(contrastNeighborhood - ...
                        currentContrast) <= tolerance);
                currentSupport = ...
                    state.weightedObservationSupport( ...
                        rowIndex, columnIndex);
                if ~isempty(neighborSupport) && ...
                        currentSupport <= max(neighborSupport)
                    continue;
                end

                if useLogOddsContrast && ...
                        ~isempty(neighborSupport)
                    supportProminence = ...
                        (currentSupport - ...
                            median(neighborSupport)) / ...
                        max(abs(currentSupport), eps);
                    prominence = max( ...
                        prominence, ...
                        minimumContrastProminence * ...
                            supportProminence / ...
                            minimumPlateauSupportProminence);
                end
            end
        end

        if prominence < minimumContrastProminence
            continue;
        end

        uncertaintyRadius = estimateUncertaintyRadius( ...
            state.probabilityMap, ...
            rowIndex, ...
            columnIndex, ...
            radius + 1, ...
            state.gridSize);

        candidatePeaks(end+1,1) = struct( ...
            'row', rowIndex, ...
            'column', columnIndex, ...
            'probability', probability, ...
            'logOdds', state.logOddsMap(rowIndex, columnIndex), ...
            'prominence', prominence, ...
            'uncertaintyRadius', uncertaintyRadius, ...
            'sourceType', "MAP"); %#ok<AGROW>

    end
end

if ~isempty(candidatePeaks)
    if useLogOddsContrast
        [~, order] = sort([candidatePeaks.logOdds], 'descend');
    else
        [~, order] = sort([candidatePeaks.probability], 'descend');
    end
    candidatePeaks = candidatePeaks(order);

    for candidateIndex = 1:numel(candidatePeaks)
        candidatePeak = candidatePeaks(candidateIndex);
        isSeparated = true;

        for selectedIndex = 1:numel(peaks)
            distance = hypot( ...
                candidatePeak.row - peaks(selectedIndex).row, ...
                candidatePeak.column - ...
                    peaks(selectedIndex).column);
            if distance < bayesianConfig.minimumPeakSeparation
                isSeparated = false;
                break;
            end
        end

        if isSeparated
            peaks(end+1,1) = candidatePeak; %#ok<AGROW>
        end

        if numel(peaks) >= ...
                bayesianConfig.maximumPeaksPerUpdate
            break;
        end
    end
end

state.lastAdaptiveThreshold = adaptiveThreshold;
state.lastBackgroundMedian = backgroundMedian;
state.lastBackgroundRobustSigma = backgroundRobustSigma;
state.lastCandidatePeakCount = numel(peaks);
state.lastPeaks = peaks;

end


function localizationConfig = readLocalizationConfig(state, config)

if isfield(state, 'localizationMethod') && ...
        lower(string(state.localizationMethod)) == ...
        "spatialbayesianfusion"
    localizationConfig = config.spatialBayesian;
else
    localizationConfig = config.bayesian;
end

end


function radius = estimateUncertaintyRadius( ...
    probabilityMap, ...
    centerRow, ...
    centerColumn, ...
    neighborhoodRadius, ...
    gridSize)

rowRange = max(1, centerRow-neighborhoodRadius): ...
    min(gridSize(1), centerRow+neighborhoodRadius);
columnRange = max(1, centerColumn-neighborhoodRadius): ...
    min(gridSize(2), centerColumn+neighborhoodRadius);
[rowGrid, columnGrid] = ndgrid(rowRange, columnRange);
weights = probabilityMap(rowRange, columnRange);
weights = max(0, weights - median(weights(:)));

if sum(weights(:)) <= eps
    radius = neighborhoodRadius;
    return;
end

distanceSquared = ...
    (rowGrid - centerRow).^2 + ...
    (columnGrid - centerColumn).^2;
radius = sqrt(sum(weights(:) .* distanceSquared(:)) / ...
    sum(weights(:)));
radius = max(0.5, radius);

end


function peaks = emptyPeakArray()

peaks = struct( ...
    'row', {}, ...
    'column', {}, ...
    'probability', {}, ...
    'logOdds', {}, ...
    'prominence', {}, ...
    'uncertaintyRadius', {}, ...
    'sourceType', {});

end
