function [peaks, diagnostics] = ...
    extractRangedMeasurementPeaks(processedPacket, state)
%% ============================================================
% تحويل قياسات UWB ذات المدى والاتجاه إلى فرضيات مكانية مستقلة.
%
% لا تستخدم هذه الدالة Ground Truth أو عدد الضحايا. وهي لا تستبدل
% الخريطة البايزية؛ بل تحفظ هوية المصادر التي تضيع عند جمع عدة قياسات
% في سطح Log-Odds واحد مشبع أو متصل.
%% ============================================================

config = constants();
spatialConfig = config.spatialBayesian;
peaks = emptyPeakArray();
diagnostics = createDiagnostics();

if ~isstruct(processedPacket) || ...
        ~isfield(processedPacket, 'probePosition') || ...
        numel(processedPacket.probePosition) < 2 || ...
        ~isfield(processedPacket, 'spatialObservations') || ...
        ~isstruct(processedPacket.spatialObservations) || ...
        ~isfield(processedPacket.spatialObservations, 'radar')
    return;
end

probePosition = double( ...
    processedPacket.probePosition(1:2));
observations = ...
    processedPacket.spatialObservations.radar;

if ~isstruct(observations) || isempty(observations)
    return;
end

diagnostics.inputObservationCount = numel(observations);
candidatePeaks = emptyPeakArray();
candidateScores = zeros(0,1);

for observationIndex = 1:numel(observations)
    observation = observations(observationIndex);

    if ~isUsableRangedObservation( ...
            observation, spatialConfig)
        diagnostics.rejectedObservationCount = ...
            diagnostics.rejectedObservationCount + 1;
        continue;
    end

    periodicity = max( ...
        double(observation.breathingPeriodicity), ...
        double(observation.heartbeatPeriodicity));
    confidence = double(observation.confidence);
    strength = double(observation.strength);
    measurementQuality = ...
        spatialConfig.rangedMeasurementConfidenceWeight * ...
            confidence + ...
        spatialConfig.rangedMeasurementStrengthWeight * ...
            strength + ...
        spatialConfig.rangedMeasurementPeriodicityWeight * ...
            periodicity;
    measurementQuality = max(0,min(1,measurementQuality));

    measuredRange = double(observation.range);
    measuredBearing = double(observation.bearing);
    rowPosition = probePosition(1) + ...
        measuredRange * sind(measuredBearing);
    columnPosition = probePosition(2) + ...
        measuredRange * cosd(measuredBearing);

    if ~isInsideGrid(rowPosition,columnPosition,state)
        diagnostics.outOfGridObservationCount = ...
            diagnostics.outOfGridObservationCount + 1;
        continue;
    end

    rangeStd = double(observation.rangeStd);
    bearingStdRadians = deg2rad( ...
        double(observation.bearingStd));
    uncertaintyRadius = sqrt( ...
        rangeStd^2 + ...
        (measuredRange*bearingStdRadians)^2);
    uncertaintyRadius = min( ...
        spatialConfig.rangedMeasurementMaximumUncertaintyRadius, ...
        max(spatialConfig.rangedMeasurementMinimumUncertaintyRadius, ...
            uncertaintyRadius));

    measurementProbability = ...
        spatialConfig.rangedMeasurementProbabilityFloor + ...
        spatialConfig.rangedMeasurementProbabilityScale * ...
            measurementQuality;
    measurementProbability = max( ...
        spatialConfig.minimumPosteriorProbability, ...
        min(spatialConfig.rangedMeasurementProbabilityCeiling, ...
            measurementProbability));

    % إن كانت الخريطة قد جمعت دليلًا أقوى عند الإسقاط نفسه، يُستخدم
    % ذلك لتقدير الوجود فقط. هوية المصدر تبقى من قياس الرادار المباشر.
    mapProbability = readMapProbability( ...
        state,rowPosition,columnPosition);
    probability = max( ...
        measurementProbability,mapProbability);
    probability = min(1-eps,max(eps,probability));

    candidatePeaks(end+1,1) = struct( ... %#ok<AGROW>
        'row', rowPosition, ...
        'column', columnPosition, ...
        'probability', probability, ...
        'logOdds', log(probability/(1-probability)), ...
        'prominence', measurementQuality, ...
        'uncertaintyRadius', uncertaintyRadius, ...
        'sourceType', "RANGED_MEASUREMENT");
    candidateScores(end+1,1) = ... %#ok<AGROW>
        measurementQuality / max(uncertaintyRadius,eps);
end

diagnostics.acceptedObservationCount = ...
    numel(candidatePeaks);

if isempty(candidatePeaks)
    return;
end

[~,order] = sort(candidateScores,'descend');
candidatePeaks = candidatePeaks(order);

for candidateIndex = 1:numel(candidatePeaks)
    candidate = candidatePeaks(candidateIndex);

    if ~isempty(peaks)
        distances = hypot( ...
            [peaks.row]' - candidate.row, ...
            [peaks.column]' - candidate.column);
        if any(distances < ...
                spatialConfig.rangedMeasurementSameUpdateMergeDistance)
            diagnostics.duplicateObservationCount = ...
                diagnostics.duplicateObservationCount + 1;
            continue;
        end
    end

    peaks(end+1,1) = candidate; %#ok<AGROW>

    if numel(peaks) >= ...
            spatialConfig.maximumPeaksPerUpdate
        break;
    end
end

diagnostics.outputPeakCount = numel(peaks);

end


function isUsable = isUsableRangedObservation( ...
    observation, config)

requiredFields = { ...
    'range','rangeStd','bearing','bearingStd', ...
    'strength','confidence','breathingPeriodicity', ...
    'heartbeatPeriodicity'};

isUsable = isstruct(observation) && ...
    all(isfield(observation,requiredFields));

if ~isUsable
    return;
end

numericFields = requiredFields(1:8);
hasScalarNumericFields = all(cellfun( ...
    @(fieldName) isnumeric(observation.(fieldName)) && ...
        isscalar(observation.(fieldName)), ...
    numericFields));

if ~hasScalarNumericFields
    isUsable = false;
    return;
end

numericValues = cellfun( ...
    @(fieldName) double(observation.(fieldName)), ...
    numericFields);

if any(~isfinite(numericValues))
    isUsable = false;
    return;
end

periodicity = max( ...
    double(observation.breathingPeriodicity), ...
    double(observation.heartbeatPeriodicity));

isUsable = ...
    observation.range > 0 && ...
    observation.rangeStd > 0 && ...
    observation.bearingStd > 0 && ...
    observation.confidence >= ...
        config.rangedMeasurementMinimumConfidence && ...
    observation.strength >= ...
        config.rangedMeasurementMinimumStrength && ...
    periodicity >= ...
        config.rangedMeasurementMinimumPeriodicity;

end


function isInside = isInsideGrid(row,column,state)

isInside = isfield(state,'gridSize') && ...
    numel(state.gridSize) >= 2 && ...
    isfinite(row) && isfinite(column) && ...
    row >= 1 && row <= state.gridSize(1) && ...
    column >= 1 && column <= state.gridSize(2);

end


function probability = readMapProbability( ...
    state,rowPosition,columnPosition)

probability = 0;

if ~isfield(state,'probabilityMap') || ...
        isempty(state.probabilityMap)
    return;
end

row = round(rowPosition);
column = round(columnPosition);

if row < 1 || row > size(state.probabilityMap,1) || ...
        column < 1 || column > size(state.probabilityMap,2)
    return;
end

candidate = state.probabilityMap(row,column);
if isfinite(candidate)
    probability = max(0,min(1-eps,double(candidate)));
end

end


function diagnostics = createDiagnostics()

diagnostics = struct( ...
    'inputObservationCount', 0, ...
    'acceptedObservationCount', 0, ...
    'rejectedObservationCount', 0, ...
    'outOfGridObservationCount', 0, ...
    'duplicateObservationCount', 0, ...
    'outputPeakCount', 0);

end


function peaks = emptyPeakArray()

peaks = struct( ...
    'row', {}, ...
    'column', {}, ...
    'probability', {}, ...
    'logOdds', {}, ...
    'prominence', {}, ...
    'uncertaintyRadius', {}, ...
    'sourceType', {});

end
