function [localizationPacket, state] = ...
    spatialBayesianLocalizationManager( ...
        scenario, processedPacket, fusionPacket, state)
%% ============================================================
% مدير v4: Spatial Bayesian Multi-Sensor Fusion.
%% ============================================================

[state, ~] = updateSpatialBayesianMap( ...
    state, scenario, processedPacket);
[mapPeaks, state] = detectBayesianPosteriorPeaks(state);
[rangedMeasurementPeaks, rangedDiagnostics] = ...
    extractRangedMeasurementPeaks(processedPacket,state);
peaks = combineSpatialTrackingPeaks( ...
    mapPeaks,rangedMeasurementPeaks);
state.lastMapPeaks = mapPeaks;
state.lastRangedMeasurementPeaks = ...
    rangedMeasurementPeaks;
state.lastRangedMeasurementDiagnostics = ...
    rangedDiagnostics;
state.lastPeaks = peaks;
state.lastCandidatePeakCount = numel(peaks);
state = updateBayesianVictimTracks( ...
    state, peaks, processedPacket.probePosition);
estimatedLocation = buildEstimatedLocation( ...
    peaks, processedPacket.probePosition);

candidate = struct( ...
    'isVictim', estimatedLocation.isDetected, ...
    'position', processedPacket.probePosition, ...
    'score', fusionPacket.fusionScore, ...
    'confidence', fusionPacket.confidence);
localizationPacket = buildLocalizationPacket( ...
    fusionPacket, candidate, estimatedLocation);
localizationPacket.localizationMethod = ...
    "spatialBayesianFusion";
localizationPacket.posteriorProbability = ...
    estimatedLocation.confidence;

end


function estimatedLocation = buildEstimatedLocation(peaks, probePosition)

estimatedLocation = struct( ...
    'isDetected', false, 'position', [], 'confidence', 0, ...
    'peakValue', 0, 'supportingCells', 0, ...
    'candidatePeakCount', numel(peaks), 'selectionScore', 0, ...
    'sourceType', "UNKNOWN", ...
    'candidatePositions', zeros(0,2), ...
    'candidateConfidences', zeros(0,1), ...
    'candidateSourceTypes', strings(0,1));
if isempty(peaks)
    return;
end

estimatedLocation.candidatePositions = [ ...
    [peaks.row]',[peaks.column]'];
estimatedLocation.candidateConfidences = ...
    [peaks.probability]';
estimatedLocation.candidateSourceTypes = ...
    string({peaks.sourceType})';

probabilities = [peaks.probability];
distances = zeros(1,numel(peaks));
for index = 1:numel(peaks)
    distances(index) = hypot(peaks(index).row-probePosition(1), ...
        peaks(index).column-probePosition(2));
end
distanceScale = max(1, median(distances)+1);
selectionScores = 0.85*probabilities + ...
    0.15*exp(-distances/distanceScale);
[selectionScore, selectedIndex] = max(selectionScores);
selected = peaks(selectedIndex);
estimatedLocation.isDetected = true;
estimatedLocation.position = [selected.row, selected.column];
estimatedLocation.confidence = selected.probability;
estimatedLocation.peakValue = selected.probability;
estimatedLocation.supportingCells = 1;
estimatedLocation.selectionScore = selectionScore;
estimatedLocation.sourceType = string(selected.sourceType);

end
