function [state, updateDiagnostics] = updateBayesianTBDMap( ...
    state, ...
    scenario, ...
    processedPacket)
%% ============================================================
% تحديث خريطة Log-Odds باستخدام القياسات الخام بعد المعالجة.
% يدمج النظام Log Bayes Factors ولا يحوّل Fusion Score إلى احتمال.
%% ============================================================

validateState(state, scenario);

config = constants();
sensorConfigs = sensorConfiguration();
probePosition = round(processedPacket.probePosition(1:2));

maximumRange = max([ ...
    sensorConfigs.radar.detectionRange, ...
    sensorConfigs.thermal.detectionRange, ...
    sensorConfigs.acoustic.detectionRange]);
updateRadius = max(1, ceil( ...
    maximumRange * ...
    config.bayesian.maximumUpdateRangeScale));

minimumRow = max(1, probePosition(1) - updateRadius);
maximumRow = min(state.gridSize(1), ...
    probePosition(1) + updateRadius);
minimumColumn = max(1, probePosition(2) - updateRadius);
maximumColumn = min(state.gridSize(2), ...
    probePosition(2) + updateRadius);

reliability = readObservableReliability(processedPacket);
meanReliability = mean(reliability);

state.updateCount = state.updateCount + 1;
state.lastProbePosition = probePosition;
updatedCellCount = 0;

for rowIndex = minimumRow:maximumRow
    for columnIndex = minimumColumn:maximumColumn

        distanceSquared = ...
            (rowIndex - probePosition(1))^2 + ...
            (columnIndex - probePosition(2))^2;

        if distanceSquared > updateRadius^2
            continue;
        end

        likelihood = ...
            calculateBayesianMeasurementLogBayesFactors( ...
                processedPacket, ...
                scenario, ...
                probePosition, ...
                [rowIndex, columnIndex]);

        sensorLogBayesFactors = [ ...
            likelihood.radar.logBayesFactor, ...
            likelihood.thermal.logBayesFactor, ...
            likelihood.acoustic.logBayesFactor];

        temperedSensorEvidence = ...
            reliability .* sensorLogBayesFactors;

        combinedEvidence = ...
            config.bayesian.sensorDependenceDiscount * ...
            sum(temperedSensorEvidence);

        oldCenteredLogOdds = ...
            state.logOddsMap(rowIndex, columnIndex) - ...
            state.priorLogOdds;

        updatedLogOdds = ...
            state.priorLogOdds + ...
            config.bayesian.localEvidenceRetention * ...
                oldCenteredLogOdds + ...
            config.bayesian.informationGain * ...
                combinedEvidence;

        maximumAbsoluteLogOdds = ...
            config.bayesian.maximumAbsoluteLogOdds;
        state.logOddsMap(rowIndex, columnIndex) = max( ...
            -maximumAbsoluteLogOdds, ...
            min(maximumAbsoluteLogOdds, updatedLogOdds));

        state.sensorLogBayesFactorMaps.radar( ...
            rowIndex, columnIndex) = updateSensorEvidence( ...
                state.sensorLogBayesFactorMaps.radar( ...
                    rowIndex, columnIndex), ...
                temperedSensorEvidence(1), ...
                config.bayesian);
        state.sensorLogBayesFactorMaps.thermal( ...
            rowIndex, columnIndex) = updateSensorEvidence( ...
                state.sensorLogBayesFactorMaps.thermal( ...
                    rowIndex, columnIndex), ...
                temperedSensorEvidence(2), ...
                config.bayesian);
        state.sensorLogBayesFactorMaps.acoustic( ...
            rowIndex, columnIndex) = updateSensorEvidence( ...
                state.sensorLogBayesFactorMaps.acoustic( ...
                    rowIndex, columnIndex), ...
                temperedSensorEvidence(3), ...
                config.bayesian);

        state.observationCount(rowIndex, columnIndex) = ...
            state.observationCount(rowIndex, columnIndex) + 1;
        state.weightedObservationSupport(rowIndex, columnIndex) = ...
            state.weightedObservationSupport(rowIndex, columnIndex) + ...
            meanReliability;
        state.lastObservationStep(rowIndex, columnIndex) = ...
            state.updateCount;

        updatedCellCount = updatedCellCount + 1;

    end
end

state.probabilityMap = stableLogistic(state.logOddsMap);

updateDiagnostics = struct();
updateDiagnostics.updatedCellCount = updatedCellCount;
updateDiagnostics.probePosition = probePosition;
updateDiagnostics.sensorReliability = reliability;
updateDiagnostics.maximumPosteriorProbability = ...
    max(state.probabilityMap(:));

end


function updatedEvidence = updateSensorEvidence( ...
    previousEvidence, ...
    currentEvidence, ...
    config)

updatedEvidence = ...
    config.localEvidenceRetention * previousEvidence + ...
    config.informationGain * currentEvidence;
updatedEvidence = max( ...
    -config.maximumAbsoluteLogOdds, ...
    min(config.maximumAbsoluteLogOdds, updatedEvidence));

end


function reliability = readObservableReliability(processedPacket)

report = processedPacket.qualityReport;
fieldNames = { ...
    'radarReliability', ...
    'thermalReliability', ...
    'acousticReliability'};
reliability = zeros(1,3);

for index = 1:3
    if isfield(report, fieldNames{index}) && ...
            isscalar(report.(fieldNames{index})) && ...
            isfinite(report.(fieldNames{index}))
        reliability(index) = max(0, min(1, ...
            report.(fieldNames{index})));
    end
end

end


function probability = stableLogistic(logOdds)

probability = zeros(size(logOdds));
positiveMask = logOdds >= 0;
probability(positiveMask) = ...
    1 ./ (1 + exp(-logOdds(positiveMask)));
negativeExponent = exp(logOdds(~positiveMask));
probability(~positiveMask) = ...
    negativeExponent ./ (1 + negativeExponent);

end


function validateState(state, scenario)

requiredFields = { ...
    'gridSize', ...
    'logOddsMap', ...
    'probabilityMap', ...
    'observationCount'};

if ~isstruct(state) || ...
        ~all(isfield(state, requiredFields))
    error( ...
        "updateBayesianTBDMap:InvalidState", ...
        "Bayesian localization state is incomplete.");
end

if ~isstruct(scenario) || ...
        ~isfield(scenario, 'gridSize') || ...
        ~isequal(double(state.gridSize), ...
            double(scenario.gridSize(1:2)))
    error( ...
        "updateBayesianTBDMap:GridMismatch", ...
        "Scenario and Bayesian state grid sizes do not match.");
end

end
