function evidenceMap = getEvidenceMapForDisplay(memory)
%% ============================================================
% استخراج خريطة الأدلة للرسم مع دعم بنية الذاكرة الحالية والقديمة
%% ============================================================

evidenceMap = zeros(0,0);

if ~isstruct(memory)
    return;
end

if isfield(memory, 'localizationMethod') && ...
        any(lower(string(memory.localizationMethod)) == ...
        ["bayesiantbd", "spatialbayesianfusion"]) && ...
        isfield(memory, 'bayesianLocalizationState') && ...
        isstruct(memory.bayesianLocalizationState) && ...
        isfield(memory.bayesianLocalizationState, ...
            'probabilityMap') && ...
        isnumeric(memory.bayesianLocalizationState.probabilityMap) && ...
        ~isempty(memory.bayesianLocalizationState.probabilityMap)

    evidenceMap = ...
        memory.bayesianLocalizationState.probabilityMap;
    return;

end

if isfield(memory, 'localizationState') && ...
        isstruct(memory.localizationState) && ...
        isfield(memory.localizationState, 'evidenceMap') && ...
        isnumeric(memory.localizationState.evidenceMap) && ...
        ~isempty(memory.localizationState.evidenceMap)

    evidenceMap = memory.localizationState.evidenceMap;
    return;

end

if isfield(memory, 'evidenceMap') && ...
        isnumeric(memory.evidenceMap) && ...
        ~isempty(memory.evidenceMap)

    evidenceMap = memory.evidenceMap;
    % مسار توافق للنتائج القديمة فقط.

end

end
