function observations = sanitizeSpatialObservationSet(observations)
%% ============================================================
% توحيد وفلترة مجموعة القياسات المكانية دون استخدام Ground Truth.
%% ============================================================

emptySet = struct( ...
    'range', {}, 'rangeStd', {}, ...
    'bearing', {}, 'bearingStd', {}, ...
    'strength', {}, 'confidence', {}, ...
    'breathingPeriodicity', {}, 'heartbeatPeriodicity', {}, ...
    'sensorName', {}, 'eventType', {});

if ~isstruct(observations) || isempty(observations)
    observations = emptySet;
    return;
end

cleaned = emptySet;
requiredFields = { ...
    'range', 'rangeStd', 'bearing', 'bearingStd', ...
    'strength', 'confidence', 'breathingPeriodicity', ...
    'heartbeatPeriodicity', 'sensorName', 'eventType'};

for index = 1:numel(observations)
    observation = observations(index);
    if ~all(isfield(observation, requiredFields))
        continue;
    end

    if ~isscalar(observation.bearing) || ...
            ~isfinite(observation.bearing) || ...
            ~isscalar(observation.bearingStd) || ...
            ~isfinite(observation.bearingStd) || ...
            observation.bearingStd <= 0 || ...
            ~isscalar(observation.strength) || ...
            ~isfinite(observation.strength) || ...
            ~isscalar(observation.confidence) || ...
            ~isfinite(observation.confidence) || ...
            ~isscalar(observation.breathingPeriodicity) || ...
            ~isfinite(observation.breathingPeriodicity) || ...
            ~isscalar(observation.heartbeatPeriodicity) || ...
            ~isfinite(observation.heartbeatPeriodicity)
        continue;
    end

    hasRange = isscalar(observation.range) && ...
        isfinite(observation.range) && observation.range >= 0;
    if hasRange
        if ~isscalar(observation.rangeStd) || ...
                ~isfinite(observation.rangeStd) || ...
                observation.rangeStd <= 0
            continue;
        end
        cleanRange = double(observation.range);
        cleanRangeStd = max(0.05, double(observation.rangeStd));
    else
        cleanRange = NaN;
        cleanRangeStd = Inf;
    end

    cleaned(end+1,1) = struct( ... %#ok<AGROW>
        'range', cleanRange, ...
        'rangeStd', cleanRangeStd, ...
        'bearing', wrapAngle180(double(observation.bearing)), ...
        'bearingStd', max(0.25, double(observation.bearingStd)), ...
        'strength', max(0, min(1, double(observation.strength))), ...
        'confidence', max(0, min(1, ...
            double(observation.confidence))), ...
        'breathingPeriodicity', max(0, min(1, ...
            double(observation.breathingPeriodicity))), ...
        'heartbeatPeriodicity', max(0, min(1, ...
            double(observation.heartbeatPeriodicity))), ...
        'sensorName', string(observation.sensorName), ...
        'eventType', string(observation.eventType));
end

observations = cleaned;

end


function angle = wrapAngle180(angle)

angle = mod(angle + 180, 360) - 180;

end
