function record = buildTelemetryLifecycleRecord( ...
    eventType, missionId, sequence, scenario, simulationResult)
%% ============================================================
% Lifecycle telemetry: MISSION_STARTED / MISSION_COMPLETED.
% لا يُسمح بإدخال Ground Truth في سجل Telemetry التشغيلي.
%% ============================================================

record = struct();
record.schemaVersion = "1.1";
record.contractType = "mission-telemetry";
record.eventType = string(eventType);
record.missionId = string(missionId);
record.sequence = double(sequence);
record.timestampUtc = telemetryTimestampUtc();
record.containsGroundTruth = false;

if string(eventType) == "MISSION_STARTED"
    record.status = "RUNNING";
    record.scenario = struct( ...
        'scenarioType', string(scenario.type), ...
        'randomSeed', double(scenario.randomSeed), ...
        'gridSize', double(scenario.gridSize(1:2)), ...
        'numVictims', double(scenario.numVictims), ...
        'debrisDensity', double(scenario.debrisDensity), ...
        'noiseLevel', double(scenario.noiseLevel), ...
        'burialDepth', double(scenario.burialDepth), ...
        'vitalStrength', double(scenario.vitalStrength));
elseif string(eventType) == "MISSION_COMPLETED"
    record.status = "COMPLETED";
    record.summary = struct( ...
        'systemDetectionCount', double(simulationResult.systemDetectionCount), ...
        'fusionHistorySize', double(simulationResult.fusionHistorySize), ...
        'maximumFusionScore', telemetryFiniteOrEmpty( ...
            simulationResult.maximumFusionScore), ...
        'meanFusionScore', telemetryFiniteOrEmpty( ...
            simulationResult.meanFusionScore));
else
    error( ...
        "buildTelemetryLifecycleRecord:UnsupportedEvent", ...
        "Unsupported lifecycle event: %s", string(eventType));
end

end


function value = telemetryFiniteOrEmpty(value)
value = double(value);
if isempty(value) || any(~isfinite(value(:)))
    value = [];
end
end


function value = telemetryTimestampUtc()
value = string(datetime( ...
    'now', ...
    'TimeZone','UTC', ...
    'Format',"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"));
end
