function vitalityPacket = buildVitalityPacket( ...
    localizationPacket, ...
    fusionPacket, ...
    temporalStability, ...
    vitalityIndex, ...
    victimCondition)

vitalityPacket = struct();

vitalityPacket.isVictimDetected = ...
    localizationPacket.isVictimDetected;

vitalityPacket.estimatedPosition = ...
    localizationPacket.estimatedPosition;

vitalityPacket.localizationConfidence = ...
    localizationPacket.localizationConfidence;

if isfield(localizationPacket,'sourceType')
    vitalityPacket.sourceType = ...
        string(localizationPacket.sourceType);
else
    vitalityPacket.sourceType = "UNKNOWN";
end

vitalityPacket.probePosition = ...
    localizationPacket.probePosition;

vitalityPacket.fusionScore = ...
    fusionPacket.fusionScore;

vitalityPacket.fusionConfidence = ...
    fusionPacket.confidence;

vitalityPacket.temporalStability = ...
    temporalStability;

vitalityPacket.vitalityIndex = ...
    vitalityIndex;

vitalityPacket.victimCondition = ...
    victimCondition;

vitalityPacket.timestamp = ...
    fusionPacket.timestamp;

vitalityPacket.status = ...
    fusionPacket.status;

end
