function vitalityIndex = calculateVitalityIndex( ...
    fusionPacket, ...
    localizationPacket, ...
    temporalStability)

Sf = fusionPacket.fusionScore;
Cf = fusionPacket.confidence;
Cl = localizationPacket.localizationConfidence;
Ts = temporalStability;

alpha = 0.50;
beta = 0.20;
gamma = 0.15;
delta = 0.15;

bias = 0.50;

x = ...
    alpha*Sf + ...
    beta*Cf + ...
    gamma*Ts + ...
    delta*Cl - ...
    bias;

vitalityIndex = ...
    1 ./ (1 + exp(-8*x));

vitalityIndex = ...
    max(0,min(1,vitalityIndex));

end