function acousticOutput = acousticSimulation(scenario, probe)
%% محاكاة طاقة صوتية تتضمن تنفسًا ضعيفًا وأحداث نداء/طرق متقطعة

sensorConfigs = sensorConfiguration();
sensorConfig = sensorConfigs.acoustic;
acousticOutput = baseSensorModel( ...
    scenario, probe, sensorConfig);
acousticOutput.spatialObservations = generateSpatialObservations( ...
    scenario, probe, sensorConfig);

acousticOutput.physicalReading = ...
    acousticOutput.normalizedValue * sensorConfig.physicalMax;
acousticOutput.physicalUnit = sensorConfig.physicalUnit;

referencePressure = 20e-6;
acousticOutput.soundPressureLevelDb = 20 * log10( ...
    max(acousticOutput.physicalReading, referencePressure) / ...
    referencePressure);

logger( ...
    "DEBUG", ...
    "Acoustic [%d,%d]: y=%.4f, SNR=%.2f dB, rho=%.3f", ...
    probe.position(1), probe.position(2), ...
    acousticOutput.normalizedValue, ...
    acousticOutput.snrDb, ...
    acousticOutput.reliability);

end
