function sensorOutput = baseSensorModel( ...
    scenario, ...
    probe, ...
    sensorConfig)
%% ============================================================
% نموذج قياس احتمالي مشترك للحساسات الثلاثة
%
% لكل ضحية: مصدر حيوي × انتقال المسار. تجمع مساهمات الضحايا
% كطاقة غير مترابطة، ثم تضاف ضوضاء قياس صفرية المتوسط.
%% ============================================================

numberOfVictims = size(scenario.victims,1);
contributions = zeros(numberOfVictims,1);
transmissions = zeros(numberOfVictims,1);
pathNoiseLevels = zeros(numberOfVictims,1);

for victimIndex = 1:numberOfVictims

    [transmission, ~, context] = ...
        sensorAttenuationModel( ...
            scenario, ...
            probe, ...
            sensorConfig, ...
            victimIndex);

    activityGain = calculateActivityGain( ...
        sensorConfig, ...
        context.vitalStrength);

    sourceVariation = max(0, ...
        1 + sensorConfig.sourceVariationStd * randn());

    sourceStrength = ...
        context.vitalStrength * activityGain * sourceVariation;

    contributions(victimIndex) = ...
        sourceStrength * transmission;
    transmissions(victimIndex) = transmission;
    pathNoiseLevels(victimIndex) = context.meanNoise;

end

if isempty(contributions)
    signalComponent = 0;
    dominantVictimIndex = NaN;
    dominantTransmission = 0;
    pathNoiseLevel = 0;
else
    signalComponent = sqrt(sum(contributions.^2));
    [~, dominantVictimIndex] = max(contributions);
    dominantTransmission = ...
        transmissions(dominantVictimIndex);
    pathNoiseLevel = ...
        pathNoiseLevels(dominantVictimIndex);
end

signalComponent = max(0, min(1, signalComponent));

    [noiseSample, noiseStd, observableNoiseStd] = sensorNoiseModel( ...
    scenario, ...
    probe, ...
    sensorConfig, ...
    pathNoiseLevel);

normalizedValue = max(0, min(1, ...
    signalComponent + noiseSample));

[reliability, snrDb] = sensorReliabilityModel( ...
    signalComponent, ...
    noiseStd, ...
    dominantTransmission, ...
    sensorConfig);

sensorOutput = struct();
sensorOutput.sensorName = sensorConfig.name;
sensorOutput.normalizedValue = normalizedValue;
sensorOutput.value = normalizedValue;
sensorOutput.signalComponent = signalComponent;
sensorOutput.rawSignal = signalComponent;
sensorOutput.noise = noiseSample;
    sensorOutput.noiseStd = noiseStd;
    sensorOutput.observableNoiseStd = observableNoiseStd;
sensorOutput.snrDb = snrDb;
    sensorOutput.reliability = reliability;
    sensorOutput.observableReliability = ...
        calculateObservableReliability( ...
            observableNoiseStd, ...
            sensorConfig);
sensorOutput.pathTransmission = dominantTransmission;
sensorOutput.status = "VALID";
% لا تُصدّر هوية الضحية أو مسافتها الحقيقية خارج مولد القياس.

end


function reliability = calculateObservableReliability( ...
    observableNoiseStd, ...
    sensorConfig)

maximumNoiseIncrement = max( ...
    eps, ...
    sensorConfig.noiseStdScale * ...
    sensorConfig.noiseSensitivity);

noiseFraction = ...
    (observableNoiseStd - sensorConfig.baseNoiseStd) / ...
    maximumNoiseIncrement;

noiseFraction = max(0, min(1, noiseFraction));

reliability = ...
    sensorConfig.minimumReliability + ...
    (1 - sensorConfig.minimumReliability) * ...
    (1 - noiseFraction);

reliability = max( ...
    sensorConfig.minimumReliability, ...
    min(1, reliability));

end


function activityGain = calculateActivityGain( ...
    sensorConfig, ...
    vitalStrength)

if string(sensorConfig.sourceModel) == "INTERMITTENT"
    eventProbability = sensorConfig.eventProbability * ...
        (0.5 + 0.5 * vitalStrength);
    eventActive = rand() < min(1, eventProbability);
    activityGain = sensorConfig.continuousActivityFloor + ...
        (1 - sensorConfig.continuousActivityFloor) * ...
        double(eventActive);
else
    activityGain = 1;
end

end
