function radarOutput = radarSimulation(scenario, probe)
%% محاكاة UWB radar اعتمادًا على الحركة الدقيقة ومسار الانتشار

sensorConfigs = sensorConfiguration();
sensorConfig = sensorConfigs.radar;
radarOutput = baseSensorModel( ...
    scenario, probe, sensorConfig);
radarOutput.spatialObservations = generateSpatialObservations( ...
    scenario, probe, sensorConfig);

radarOutput.physicalReading = ...
    radarOutput.normalizedValue * sensorConfig.physicalMax;
radarOutput.physicalUnit = sensorConfig.physicalUnit;

logger( ...
    "DEBUG", ...
    "Radar [%d,%d]: y=%.4f, SNR=%.2f dB, rho=%.3f", ...
    probe.position(1), probe.position(2), ...
    radarOutput.normalizedValue, ...
    radarOutput.snrDb, ...
    radarOutput.reliability);

end
