function [totalTransmission, details, context] = ...
    sensorAttenuationModel( ...
        scenario, ...
        probe, ...
        sensorConfig, ...
        victimIndex)
%% ============================================================
% حساب فقد المسار الهندسي والخسارة المادية بين المصدر والمستقبِل
%% ============================================================

context = sensorPropagationContext( ...
    scenario, ...
    probe.position, ...
    victimIndex);

normalizedDistance = ...
    context.distance / max(sensorConfig.detectionRange, eps);

distanceTransmission = 1 / ...
    (1 + normalizedDistance^sensorConfig.pathLossExponent);
% نموذج تشبع تطبيقي يحاكي اضمحلال القدرة دون تفرد عند المسافة صفر.

pathLength = max(1, context.distance);
effectiveObstacleCells = ...
    context.obstacleFraction * context.pathCellCount;

materialLossDb = ...
    pathLength * ( ...
        sensorConfig.debrisLossDbPerCell * context.meanDebris + ...
        sensorConfig.attenuationLossDbPerCell * ...
            context.meanAttenuation) + ...
    sensorConfig.obstacleLossDbPerCell * ...
        effectiveObstacleCells + ...
    sensorConfig.burialLossDb * context.burialDepth;

materialTransmission = 10^(-materialLossDb / 20);
totalTransmission = max(0, min(1, ...
    distanceTransmission * materialTransmission));

details = struct();
details.distanceTransmission = distanceTransmission;
details.materialTransmission = materialTransmission;
details.materialLossDb = materialLossDb;
details.totalTransmission = totalTransmission;

end
