function thermalOutput = thermalSimulation(scenario, probe)
%% محاكاة فرق الحرارة مع حجب شديد للمواد الصلبة والدفن

sensorConfigs = sensorConfiguration();
sensorConfig = sensorConfigs.thermal;
thermalOutput = baseSensorModel( ...
    scenario, probe, sensorConfig);
thermalOutput.spatialObservations = generateSpatialObservations( ...
    scenario, probe, sensorConfig);

thermalOutput.physicalReading = ...
    thermalOutput.normalizedValue * sensorConfig.physicalMax;
thermalOutput.physicalUnit = sensorConfig.physicalUnit;

logger( ...
    "DEBUG", ...
    "Thermal [%d,%d]: y=%.4f, SNR=%.2f dB, rho=%.3f", ...
    probe.position(1), probe.position(2), ...
    thermalOutput.normalizedValue, ...
    thermalOutput.snrDb, ...
    thermalOutput.reliability);

end
