function projectRoot = setupProjectPaths()
%% ============================================================
% Function Name : setupProjectPaths
%
% Description :
% يضيف مجلدات التنفيذ والاختبارات المعتمدة إلى MATLAB Path بترتيب ثابت.
% لا يستخدم genpath حتى لا تعود المجلدات القديمة أو الملفات المتعارضة
% إلى مسار التنفيذ دون قصد.
%% ============================================================

currentFile = mfilename('fullpath');
mainFolder = fileparts(currentFile);
projectRoot = fileparts(mainFolder);

activeFolders = { ...
    'Main', ...
    'Environment', ...
    'SensorSimulation', ...
    'Microcontroller_Interface', ...
    'SignalProcessing', ...
    'Fusion', ...
    'localization', ...
    'vitality', ...
    'PriorityRanking', ...
    'RescuePlanning', ...
    'Decision', ...
    'ProbeAgent', ...
    'Integration', ...
    'Evaluation', ...
    'Utilities', ...
    'Visualization', ...
    'Tests'};

for folderIndex = 1:numel(activeFolders)
    folderPath = fullfile(projectRoot, activeFolders{folderIndex});

    if ~isfolder(folderPath)
        error( ...
            "setupProjectPaths:MissingFolder", ...
            "Required project folder is missing: %s", ...
            folderPath);
    end

    addpath(folderPath, '-end');
end

end
