function frame = buildAcquisitionFrameV2(measurement, missionId, sequence)
%BUILDACQUISITIONFRAMEV2 Whitelist every inference input for a future MCU.
% Standalone candidate: existing mission execution is NOT changed by this file.
frame = struct('schemaVersion', "2.0", ...
    'missionId', string(missionId), 'sequence', double(sequence), ...
    'timestampUtc', string(datetime('now', 'TimeZone', 'UTC', ...
        'Format', "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")), ...
    'source', "SIMULATION", 'poseSource', "SIMULATED", ...
    'probePosition', double(measurement.probePosition(:)'), ...
    'probeHeadingDegrees', double(measurement.probeHeadingDegrees));
frame.sensors = struct();
frame.spatialObservations = struct();
for name = ["radar", "thermal", "acoustic"]
    label = char(name);
    frame.sensors.(label) = struct( ...
        'normalized', double(measurement.(label)), ...
        'physical', double(measurement.([label 'Physical'])), ...
        'unit', string(measurement.([label 'Unit'])), ...
        'reliability', double(measurement.([label 'Reliability'])), ...
        'noiseStd', double(measurement.([label 'NoiseStd'])));
    observations = measurement.spatialObservations.(label);
    wireObservations = cell(numel(observations),1);
    for k = 1:numel(observations)
        item = observations(k);
        hasRange = isnumeric(item.range) && isscalar(item.range) && ...
            isfinite(item.range) && item.range >= 0;
        if hasRange
            range = double(item.range);
            rangeStd = double(item.rangeStd);
        else
            range = 0;
            rangeStd = 0;
        end
        wireObservations{k} = struct( ...
            'hasRange', logical(hasRange), 'range', range, ...
            'rangeStd', rangeStd, 'bearing', double(item.bearing), ...
            'bearingStd', double(item.bearingStd), ...
            'strength', double(item.strength), ...
            'confidence', double(item.confidence), ...
            'breathingPeriodicity', double(item.breathingPeriodicity), ...
            'heartbeatPeriodicity', double(item.heartbeatPeriodicity), ...
            'sensorName', string(item.sensorName), ...
            'eventType', string(item.eventType));
    end
    frame.spatialObservations.(label) = wireObservations;
end
validateAcquisitionFrameV2(frame);
end
