function packet = communicationManager( ...
    radarOutput, ...
    thermalOutput, ...
    acousticOutput)

packet = ...
    buildSensorPacket( ...
    radarOutput, ...
    thermalOutput, ...
    acousticOutput);

packet = ...
    sendSensorPacket(packet);

status = ...
    receiveMCUStatus();

packet = ...
    updateMCUState( ...
    packet, ...
    status);

packet = ...
    parseMCUResponse(packet);

end