function state = initializeAcquisitionStateV2( ...
    source, missionId, poseSource)
%INITIALIZEACQUISITIONSTATEV2 Create explicit per-mission source state.
% The active demo uses SIMULATION. PROTEUS/HARDWARE are accepted as
% declarations only; requestSensorData fails closed until a provider is
% wired for either source.

if nargin < 1 || isempty(source)
    source = "SIMULATION";
end
if nargin < 2 || isempty(missionId)
    missionId = "LOCAL_MISSION";
end
if nargin < 3 || isempty(poseSource)
    if string(source) == "HARDWARE"
        poseSource = "MEASURED";
    else
        poseSource = "SIMULATED";
    end
end

source = string(source);
missionId = string(missionId);
poseSource = string(poseSource);

if ~isscalar(source) || ...
        ~ismember(source, ["SIMULATION","PROTEUS","HARDWARE"]) || ...
        ~isscalar(missionId) || ...
        isempty(regexp(char(missionId), ...
            '^[A-Za-z0-9_-]{1,80}$', 'once')) || ...
        ~isscalar(poseSource) || ...
        ~ismember(poseSource, ["SIMULATED","MEASURED"]) || ...
        (source == "HARDWARE" && poseSource ~= "MEASURED")
    error('USAR:AcquisitionV2:State', ...
        'Invalid acquisition source, mission ID, or pose source.');
end

state = struct( ...
    'schemaVersion', "2.0", ...
    'source', source, ...
    'poseSource', poseSource, ...
    'missionId', missionId, ...
    'lastSequence', 0);

end
