function validateMCUTransportResponse(frame, response)
%VALIDATEMCUTRANSPORTRESPONSE Fail closed on missing, stale or altered ACK.
validateMCUTransportFrame(frame);
expected = ["schemaVersion", "missionId", "sequence", ...
    "ack", "status", "sensors"];
if ~isstruct(response) || ~isscalar(response) || ...
        ~isequal(sort(string(fieldnames(response))), sort(expected(:))) || ...
        ~strcmp(string(response.schemaVersion), string(frame.schemaVersion)) || ...
        ~strcmp(string(response.missionId), string(frame.missionId)) || ...
        ~isequal(response.sequence, frame.sequence) || ...
        ~strcmp(string(response.ack), "ACK") || ...
        ~strcmp(string(response.status), "VALID")
    error('USAR:MCUTransport:ACK', 'Missing or mismatched MCU ACK.');
end

% Only transport-confirmed sensor values may enter the acquisition path.
if ~isstruct(response.sensors) || ...
        ~isequal(sort(string(fieldnames(response.sensors))), ...
            sort(string(fieldnames(frame.sensors))))
    error('USAR:MCUTransport:Payload', 'MCU payload differs from request.');
end
for name = ["radar", "thermal", "acoustic"]
    actual = response.sensors.(char(name));
    expectedSensor = frame.sensors.(char(name));
    if ~isstruct(actual) || ~isequal(sort(string(fieldnames(actual))), ...
            sort(string(fieldnames(expectedSensor)))) || ...
            ~isequal(actual.normalized, expectedSensor.normalized) || ...
            ~isequal(actual.physical, expectedSensor.physical) || ...
            ~isequal(actual.reliability, expectedSensor.reliability) || ...
            ~strcmp(string(actual.unit), string(expectedSensor.unit))
        error('USAR:MCUTransport:Payload', ...
            'MCU payload differs from request.');
    end
end
end
