function validateMCUTransportFrame(frame)
%VALIDATEMCUTRANSPORTFRAME Reject malformed or oracle-bearing wire data.

expected = ["schemaVersion", "missionId", "sequence", ...
    "timestampUtc", "source", "probePosition", ...
    "probeHeadingDegrees", "sensors"];
if ~isstruct(frame) || ~isscalar(frame) || ...
        ~isequal(sort(string(fieldnames(frame))), sort(expected(:)))
    error('USAR:MCUFrame:Fields', 'Unexpected frame fields.');
end
if ~strcmp(string(frame.schemaVersion), "1.0") || ...
        ~strcmp(string(frame.source), "SIMULATED") || ...
        ~isscalar(string(frame.missionId)) || ...
        isempty(regexp(char(frame.missionId), ...
            '^[A-Za-z0-9_-]{1,80}$', 'once')) || ...
        ~isscalar(string(frame.timestampUtc)) || ...
        strlength(string(frame.timestampUtc)) == 0
    error('USAR:MCUFrame:Metadata', 'Invalid frame metadata.');
end
if ~isFiniteScalar(frame.sequence) || frame.sequence < 0 || ...
        frame.sequence ~= fix(frame.sequence) || ...
        ~isnumeric(frame.probePosition) || ...
        numel(frame.probePosition) ~= 2 || ...
        any(~isfinite(frame.probePosition)) || ...
        ~isFiniteScalar(frame.probeHeadingDegrees)
    error('USAR:MCUFrame:Coordinates', 'Invalid sequence or pose.');
end

names = ["radar", "thermal", "acoustic"];
if ~isstruct(frame.sensors) || ~isscalar(frame.sensors) || ...
        ~isequal(sort(string(fieldnames(frame.sensors))), sort(names(:)))
    error('USAR:MCUFrame:Sensors', 'Expected three sensor readings.');
end
sensorFields = ["normalized", "physical", "unit", "reliability"];
for name = names
    reading = frame.sensors.(char(name));
    if ~isstruct(reading) || ~isscalar(reading) || ...
            ~isequal(sort(string(fieldnames(reading))), ...
                sort(sensorFields(:))) || ...
            ~isFiniteScalar(reading.normalized) || ...
            reading.normalized < 0 || reading.normalized > 1 || ...
            ~isFiniteScalar(reading.physical) || ...
            ~isFiniteScalar(reading.reliability) || ...
            reading.reliability < 0 || reading.reliability > 1 || ...
            ~isscalar(string(reading.unit)) || ...
            strlength(string(reading.unit)) == 0 || ...
            strlength(string(reading.unit)) > 80
        error('USAR:MCUFrame:Reading', 'Invalid %s reading.', name);
    end
end
end

function tf = isFiniteScalar(value)
tf = isnumeric(value) && isscalar(value) && isreal(value) && ...
    isfinite(value);
end
