function validateAcquisitionFrameV2(frame)
%VALIDATEACQUISITIONFRAMEV2 Fail closed; never silently drop spatial inputs.
assertFields(frame, ["schemaVersion","missionId","sequence", ...
    "timestampUtc","source","poseSource","probePosition", ...
    "probeHeadingDegrees","sensors","spatialObservations"]);
if ~strcmp(string(frame.schemaVersion), "2.0") || ...
        ~isscalar(string(frame.missionId)) || ...
        isempty(regexp(char(frame.missionId), ...
            '^[A-Za-z0-9_-]{1,80}$','once')) || ...
        ~isscalar(string(frame.timestampUtc)) || ...
        strlength(string(frame.timestampUtc)) == 0 || ...
        ~isscalar(string(frame.source)) || ...
        ~ismember(string(frame.source), ...
            ["SIMULATION","PROTEUS","HARDWARE"]) || ...
        ~isscalar(string(frame.poseSource)) || ...
        ~ismember(string(frame.poseSource), ["SIMULATED","MEASURED"]) || ...
        (string(frame.source) == "HARDWARE" && ...
            string(frame.poseSource) ~= "MEASURED") || ...
        ~isFiniteScalar(frame.sequence) || ...
        frame.sequence < 1 || frame.sequence ~= fix(frame.sequence) || ...
        ~isnumeric(frame.probePosition) || ...
        numel(frame.probePosition) ~= 2 || ...
        any(~isfinite(frame.probePosition)) || ...
        ~isFiniteScalar(frame.probeHeadingDegrees)
    error('USAR:AcquisitionV2:Metadata', 'Invalid acquisition metadata or pose.');
end
names = ["radar","thermal","acoustic"];
assertFields(frame.sensors, names);
assertFields(frame.spatialObservations, names);
for name = names
    label = char(name);
    sensor = frame.sensors.(label);
    assertFields(sensor, ...
        ["normalized","physical","unit","reliability","noiseStd"]);
    if ~bounded(sensor.normalized) || ~isFiniteScalar(sensor.physical) || ...
            ~bounded(sensor.reliability) || ...
            ~isFiniteScalar(sensor.noiseStd) || sensor.noiseStd < 0 || ...
            ~isscalar(string(sensor.unit)) || ...
            strlength(string(sensor.unit)) == 0 || ...
            strlength(string(sensor.unit)) > 80
        error('USAR:AcquisitionV2:Sensor', 'Invalid %s sensor.', label);
    end
    items = frame.spatialObservations.(label);
    if isempty(items)
        continue;
    end
    if ~iscell(items) && ~isstruct(items)
        error('USAR:AcquisitionV2:Spatial', 'Invalid observation set.');
    end
    if numel(items) > 64
        error('USAR:AcquisitionV2:Spatial', 'Too many observations.');
    end
    for k = 1:numel(items)
        if iscell(items), item = items{k}; else, item = items(k); end
        assertFields(item, ["hasRange","range","rangeStd", ...
            "bearing","bearingStd","strength","confidence", ...
            "breathingPeriodicity","heartbeatPeriodicity", ...
            "sensorName","eventType"]);
        if ~isscalar(item.hasRange) || ...
                ~(islogical(item.hasRange) || isnumeric(item.hasRange)) || ...
                ~ismember(double(item.hasRange), [0 1]) || ...
                ~isFiniteScalar(item.range) || item.range < 0 || ...
                ~isFiniteScalar(item.rangeStd) || item.rangeStd < 0 || ...
                (logical(item.hasRange) && item.rangeStd <= 0) || ...
                (~logical(item.hasRange) && ...
                    (item.range ~= 0 || item.rangeStd ~= 0)) || ...
                ~isFiniteScalar(item.bearing) || ...
                abs(item.bearing) > 180 || ...
                ~isFiniteScalar(item.bearingStd) || item.bearingStd <= 0 || ...
                ~bounded(item.strength) || ~bounded(item.confidence) || ...
                ~bounded(item.breathingPeriodicity) || ...
                ~bounded(item.heartbeatPeriodicity) || ...
                ~isscalar(string(item.sensorName)) || ...
                strlength(string(item.sensorName)) == 0 || ...
                ~isscalar(string(item.eventType)) || ...
                strlength(string(item.eventType)) == 0
            error('USAR:AcquisitionV2:Spatial', ...
                'Invalid %s spatial observation.', label);
        end
    end
end
end

function assertFields(value, expected)
if ~isstruct(value) || ~isscalar(value) || ...
        ~isequal(sort(string(fieldnames(value))), sort(expected(:)))
    error('USAR:AcquisitionV2:Fields', 'Missing or unexpected fields.');
end
end

function valid = isFiniteScalar(value)
valid = isnumeric(value) && isscalar(value) && ...
    isreal(value) && isfinite(value);
end

function valid = bounded(value)
valid = isFiniteScalar(value) && value >= 0 && value <= 1;
end
